### ISSUE TITLE
Feature - auto close after picking object from outliner

### ISSUE THREAD

**Issue by JoseConseco** [stevearc/aerial.nvim#1]
Thanks for great plug. Finally simple, nice looking outliner. 
I wish there was option in config - to auto close aerial window after I have picked element from outliner  with <CR>.

**Comment by stevearc** [comment]
You could get that behavior by adding a custom mapping in `.vim/ftplugin/aerial.vim`
```vim
nnoremap <buffer> <CR> <cmd>lua require'aerial'.select()<CR><cmd>AerialClose<CR>
```
Would that work for your purposes?

**Comment by JoseConseco** [comment]
It did not work. But maybe I'm doing something wrong -  this is my setup:
![image](https://user-images.githubusercontent.com/13521338/122815903-5a9cec80-d2d6-11eb-942c-6d7031fd7184.png)

Maybe the aeria.vim should be placed in `~/.config/nvim/.vim/ftplugin/aeria.vim` ?   (nvim - is the main config folder)

 I'm also not sure why now I get this error when I open the Aerial with toggle command: :
![image](https://user-images.githubusercontent.com/13521338/122815398-b31fba00-d2d5-11eb-8f3b-1d0c79fc32a4.png)

**Comment by JoseConseco** [comment]
I tried to move the file inside .vim/ftplugin - but new mapping also did not work in there...
I disabled the default mapping, just to be sure they are not overriding the  new one but still  map <CR> shows  original mapping: 
![image](https://user-images.githubusercontent.com/13521338/122816900-91bfcd80-d2d7-11eb-817d-115d5c4cf73b.png)

**Comment by JoseConseco** [comment]
So the solution was to use  file name:    
aerial_mappings.vim
in:   ~/.config/nvim/ftplugin/aerial_mappings.vim
Now it works.  I will create new issue with the 'handle is closing'

**Comment by stevearc** [comment]
Huh...that's strange I put that exact line into `~/.config/nvim/ftplugin/aerial.vim` and it worked. Maybe this is something to do with packer and how it manages the runtimepath? I'll install packer and see if I can reproduce the issue

**Comment by stevearc** [comment]
And I just pushed up a change that should hopefully remove the "handle is already closing" error.
