### ISSUE TITLE
A bug with hls

### ISSUE THREAD

**Issue by LC0117** [stevearc/aerial.nvim#101]
**Describe the bug**
Use aerial's on_attach with hls(haskell-language-server) causes nvim to freeze and consumes huge memory, as can be seen in [this reddit post](https://www.reddit.com/r/neovim/comments/uczk28/haskell_language_server_consumes_a_lot_of_memory/) and [this issue in nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/issues/1805).
I cannot find any solution to this until I disabled hls's on_attach config:
```lua
-- in a file
-- defaults.on_attach
local function lsp_highlight_document(client)
  if client.resolved_capabilities.document_highlight then
    vim.api.nvim_create_augroup('lsp_document_highlight', {})
    vim.api.nvim_create_autocmd('CursorHold', {
      group = 'lsp_document_highlight',
      pattern = '<buffer>',
      callback = vim.lsp.buf.document_highlight,
    })
    vim.api.nvim_create_autocmd('CursorMoved', {
      group = 'lsp_document_highlight',
      pattern = '<buffer>',
      callback = vim.lsp.buf.clear_references,
    })
  end
end

function M.on_attach(client, bufnr)
  require('aerial').on_attach(client, bufnr)
  lsp_highlight_document(client)
end

-- in another file
-- after commented the line the bug disappeared 
local nlsp = require('lspconfig')
nlsp.hls.setup({
  --on_attach = defaults.on_attach,
  capabilities = defaults.capabilities,
  settings = {
    haskell = {
      formattingProvider = 'fourmolu',
    },
  },
})
```

**System information**
- OS: macOS arm64
- Neovim version: 0.7.0 stable
- AerialInfo: (since the editor freezes no output)
- Aerial config:
```lua
require('aerial').setup({
  backends = { 'lsp', 'treesitter', 'markdown' },
  close_behavior = 'auto',
  highlight_on_hover = true,
  highlight_on_jump = 300,
  max_width = { 40, 0.2 },
  manage_folds = true,
  min_width = 20,
  show_guides = true,
  filter_kind = false,
  guides = {
    mid_item = '├─',
    last_item = '╰─',
    nested_top = '│ ',
    whitespace = '  ',
  },
})
```

**To Reproduce**
1. setup hls with aerial's on_attach
2. `cabal init` in a new empty folder or `stack new <anyname>`
3. open a `*.hs` file in the above project

If possible, provide a minimal file that will trigger the issue:
the aerial setup above and with a config of hls
```
require('lspconfig').hls.setup({on_attach = <aerial_on_attach>, capabilities = ...})
```

**Screenshots**
As mentioned in the description links

**Additional context**
Or maybe it's a bug with hls?
But in hls's doc it says [textDocument/documentSymbol] is [supported](textDocument/documentSymbol)

**Comment by LC0117** [comment]
#### Addition text
single non-project `*.hs` file seems to work fine

**Comment by stevearc** [comment]
There's two bugs here.
1) hls responds to `documentSymbol` with this:
```
{ {
    children = { {
        kind = 12,
        name = "main",
        range = {
          end = {
            character = 33,
            line = 3
          },
          start = {
            character = 0,
            line = 3
          }
        },
        selectionRange = {
          end = {
            character = 33,
            line = 3
          },
          start = {
            character = 0,
            line = 3
          }
        }
      } },
    kind = 1,
    name = "Main",
    range = {
      end = {
        character = 0,
        line = 2147483647
      },
      start = {
        character = 0,
        line = 0
      }
    },
    selectionRange = {
      end = {
        character = 11,
        line = 0
      },
      start = {
        character = 7,
        line = 0
      }
    }
  } }
```
The bad line is `line = 2147483647`, which seems incorrect given that the file is 4 lines long.

2) Aerial shouldn't spin forever if it gets bad data.

I've pushed up a fix that should handle the bad data we're getting from hls. I'll file an issue on their repo about the bad symbol range and hopefully that'll get fixed at some point.

**Comment by LC0117** [comment]
Thanks for taking time digging into it and the fix! That makes me realize where the problem lies.
