### ISSUE TITLE
AerialBuffer does not update when in global mode while moving between splits

### ISSUE THREAD

**Issue by miversen33** [stevearc/aerial.nvim#102]
**Describe the bug**
When you have split buffers, AerialBuffer does not update on change between buffers. Additionally, toggling AerialBuffer while in the split that did _not_ initiate the toggle causes a second Aerial Buffer to appear

**System information**
- OS: linux (Ubuntu 20.04 LTS)
- Neovim version: 0.7 (appimage)
- AerialInfo: 
```
Aerial Info                                                                                                                                                                                             
-----------
Filetype: lua
Configured backends:
  treesitter (supported) (attached)
  lsp (not supported) [LSP client not attached]
  markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```
- Aerial config:
```lua
local excluded_filetypes_array = {'lsp-installer', 'lspinfo', 'Outline', 'help', 'packer', 'netrw', 'qf', 'dbui', 'Trouble', 'fugitive'}
require('aerial').setup({
    default_bindings = false,
    ignore = { filetypes = excluded_filetypes_array },
    placement_editor_edge = true,
    update_events = "TextChanged,InsertLeave,WinEnter,WinLeave",
    show_guides = true,
})
vim.api.nvim_set_keymap('n',  '<Enter>' , ':AerialToggle! right<CR>',  {noremap = true, silent = true})
```

**To Reproduce**
1. Open a file that is supported (I demoed this issue by opening [util.lua from this project](https://github.com/stevearc/aerial.nvim/blob/master/lua/aerial/util.lua))
2. `:AerialToggle! right`
3. `:vsplit` (or `:split`, whatever your heart desires)
4. Open a new file in your split, I used the [readme from this project](https://github.com/stevearc/aerial.nvim/blob/master/README.md)

Screenshots to show what this looks like
![readme md open](https://user-images.githubusercontent.com/2640668/167534680-75305ada-622e-47d8-b9cb-57315d12ad94.png)
![util lua open](https://user-images.githubusercontent.com/2640668/167534683-64042b28-5700-4721-b262-050c7325682a.png)

If possible, provide a minimal file that will trigger the issue:
```lua
local install_path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then 
    packer_bootstrap = vim.fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end
require('packer').startup(function(use)
    use {
        'nvim-treesitter/nvim-treesitter', run = ':TSUpdate | TSInstall lua' 
    }
    use 'stevearc/aerial.nvim'
end)
require('aerial').setup({
    default_bindings = false,
    ignore = { filetypes = excluded_filetypes_array },
    placement_editor_edge = true,
    update_events = "TextChanged,InsertLeave,WinEnter,WinLeave",
    show_guides = true,
})
vim.api.nvim_set_keymap('n', '<Enter>', ':AerialToggle! right<CR>', {noremap=true, silent=true})
```

**Screenshots**

**Additional context**
So there appears to be 2 issues at play here.
1) The autocommand _is_ caught and handled by Aerial (verified by our trusty print statement which I added right above [line 8
 in backends/util.lua](https://github.com/stevearc/aerial.nvim/blob/f1dfb0a05cd87f21175f33b3c8f4fbe4b1d77f18/lua/aerial/backends/util.lua#L7), however it doesn't actually refresh its buffer with new content
 2) The more fun issue, if you go to the other split and press `Enter` again (triggering the `:AerialToggle! right` mapped comment), you get a ![second Aerial buffer](https://user-images.githubusercontent.com/2640668/167535843-15981549-5805-428f-9264-04cfadf87ef6.png)!
 
 I dont know much about the code base here (super fascinating project by the way!) but I am guessing there is an issue with how Aerial establishes if its buffer is open. 
 
 Maybe I am using it wrong?
 
 Potentially Related: [#95](https://github.com/stevearc/aerial.nvim/issues/95)

**Comment by miversen33** [comment]
After some digging through the code, it appears this is related to how Aerial Buffer numbers are stored.
[See lua/aerial/util.lua:115](https://github.com/stevearc/aerial.nvim/blob/f1dfb0a05cd87f21175f33b3c8f4fbe4b1d77f18/lua/aerial/util.lua#L115)
```lua
M.get_buffer_from_var = function(bufnr, varname)
  local status, result_bufnr = pcall(vim.api.nvim_buf_get_var, bufnr, varname)
  if not status or result_bufnr == nil or not vim.api.nvim_buf_is_valid(result_bufnr) then
    return -1
  end
  return result_bufnr
end
```
Note from `:help nvim_buf_get_var`
```

nvim_buf_get_var({buffer}, {name})                        *nvim_buf_get_var()*
                Gets a buffer-scoped (b:) variable.

                Parameters: 
                    {buffer}  Buffer handle, or 0 for current buffer
                    {name}    Variable name

                Return: 
                    Variable value
                    ```

**Comment by miversen33** [comment]
Accidental closure, github hates me.

**Comment by stevearc** [comment]
The title of your issue mentions "when in global mode", but I don't see the option listed in your config. Have you tried setting `close_behavior = 'global'`? (The option has evolved since I named it. Probably needs to be renamed soon.) I think that will do what you want.

**Comment by miversen33** [comment]
Turns out reading is hard, that does exactly what I needed. Thanks!

**Comment by stevearc** [comment]
Glad it was an easy fix! 😄
