### ISSUE TITLE
How to configure open behavior when using `open_automatic`?

### ISSUE THREAD

**Issue by krishnakumarg1984** [stevearc/aerial.nvim#103]
This is a great plugin. Thank you for developing this!

It would be nice to have a customisable `open_behavior` when setting `open_automatic` (to either a custom function or the standard toggle key).

In particular, for some filetypes, I'd like to automatically load the aerial window with all symbols collapsed (for example for a  `lua` buffer wherein the symbols can be noisy leading to a lengthy aerial window, thereby ending up defeating the purpose of having a symbol-tree window;  for other filetypes such as `c++`, I'd like to automatically open the aerial window with its symbols-tree fully expanded).

If such a custom functionality will take a bit of time to develop, I am happy to temporarily settle for a solution wherein we set aerial to automatically open with symbols tree fully collapsed?

**Comment by stevearc** [comment]
Okay, this request kicked off a bunch of work that's been sitting in my backlog for a while. The main results:

* `:AerialTreeSetCollapseLevel` - new command to set the collapse level of the tree. Works like `foldlevel`, and in fact will sync with `foldlevel` when `config.link_tree_to_folds = true`.
* If `config.manage_folds = true` and `config.link_folds_to_tree = true`, the aerial tree will set its collapse level to match the buffer `foldlevel` upon first open.
* New `config.on_first_symbols` callback. This is called the first time a buffer receives symbols.

For your use case, you probably want to do something like
```lua
require("aerial").setup({
  on_first_symbols = function(bufnr)
    local ft = vim.api.nvim_buf_get_option(bufnr, "filetype")
    if ft == "lua" then
      require("aerial").tree_set_collapse_level(bufnr, 1)
    end
  end,
})
```

**Comment by krishnakumarg1984** [comment]
I will have a go at this early next week. Thank you for positively taking action on this issue request.

**Comment by krishnakumarg1984** [comment]
Thank you for the neat solutions suggested. While linking to the buffer's fold level is indeed a nice option, perhaps more independent control is warranted, since the idiosyncrasies of some languages mean that `buf_foldlevel ≠ symbols_foldlevel`. 

A classic example would be `latex`. While sections/subsections/equation-environments etc can be folded and considered to provide a symbol, there are a myriad of constructs that can be folded away, but yet do not correspond to a symbol for the tree outline. These could be custom environments or commands and constructs by  third-party packages etc. The symbols-tree also gets folded a lot when using `LaTeX3` i.e. using `expl-3` grammar. 

Overall, it would be nice to augment the `config.link_tree_to_folds = false` setting with `config.symbol_fold_level` that can be configured as a lua table per filetype.  This will provide independent control for buffers fold level and symbol tree fold level for those who need it.

**Comment by stevearc** [comment]
Agree that it would make sense for the `manage_folds` option to accept a filetype table. Will put that on the backlog

**Comment by stevearc** [comment]
`manage_folds` can be a filetype map now
