### ISSUE TITLE
[Feature Request] An API to output symbols structure for the current cursor position

### ISSUE THREAD

**Issue by rockyzhang24** [stevearc/aerial.nvim#105]
Hello, 

I know this plugin provides a `lualine` component for displaying the symbols structure for the current cursor position. It's fantastic, however, it is only available in `lualine`. I am wondering whether it is possible to expose an API (a function) so that we can get this symbols structure by calling the function. If so, we can integrate in any other plugins. For example, I can show this symbols structure in the `winbar` (a new feature merged this morning https://github.com/neovim/neovim/pull/18562) instead of the statusline.

I know there are some plugins offering a similar feature such as `nvim-treesitter` and `nvim-gps`. But they display the symbols structure via treesitter, not LSP. If `aerial` could expose such a API, we can display the symbols structure via LSP by setting its backends option.

Any thoughts on this? 

Thank you very much. 

---

**Update**:

Currently I try to implement this via aerial builtin function `aerial.get_location()` (https://github.com/stevearc/aerial.nvim/blob/master/lua/aerial/init.lua#L127) and the function `format_status()` for the `lualine` component (https://github.com/stevearc/aerial.nvim/blob/master/lua/lualine/components/aerial.lua#L53).

The implemented API is `output_symbols_structure(depth, separator, icons_enabled)`. 

```lua
local aerial = require('aerial')

local function format_status(symbols, depth, separator, icons_enabled)
  local parts = {}
  depth = depth or #symbols

  if depth > 0 then
    symbols = { unpack(symbols, 1, depth) }
  else
    symbols = { unpack(symbols, #symbols + 1 + depth) }
  end

  for _, symbol in ipairs(symbols) do
    if icons_enabled then
      table.insert(parts, string.format("%s %s", symbol.icon, symbol.name))
    else
      table.insert(parts, symbol.name)
    end
  end

  return table.concat(parts, separator)
end

-- The API to output the symbols structure
function output_symbols_structure(depth, separator, icons_enabled)
  local symbols = aerial.get_location(true)
  local symbols_structure = format_status(symbols, depth, separator, icons_enabled)
  print(symbols_structure)
end
```
Then we call the API by `lua output_symbols_structure(nil, ' > ', true)` and it will output the symbols structure shown below. This is really what I need. 

<img width="243" alt="image" src="https://user-images.githubusercontent.com/11582667/169169071-648fa0af-9259-4895-be11-1d21fb9c3daf.png">

Any thoughts? Thank you so much.

**Comment by rockyzhang24** [comment]
Wow, nice. So actually all exported functions in `init.lua` (i.e., `M.xxx` in `init.lua`) are the public APIs you offer to users, right? If so, it is very hard to find them for some inexperienced neovim users, do you think it will be better to add documents for them? 

Thank you.

**Comment by rockyzhang24** [comment]
Got it. Thank you so much for your words. I think you can also enable the "Wiki" page that is good place as well to share some use cases.

**Comment by rodhash** [comment]
cool! Thanks for this well written issue, didn't know MD LSP was a thing .. having a MD winbar feels way better than relying only on sidebar with Toc / outline / arial styles. I mean, arial still rocks but having a winbar makes it better.
