### ISSUE TITLE
Aerial Folds Functions Automatically when `manage_fold` is Set to `true`

### ISSUE THREAD

**Issue by Bekaboo** [stevearc/aerial.nvim#109]
**Describe the bug**
Setting `manage_fold` to true leads to aerial automatically folds functions and methods when opening a new file.

**System information**
- OS: [Ubuntu 20.04 focal(on the Windows Subsystem for Linux)]
- Neovim version: NVIM v0.7.0
                             Build type: Release
                             LuaJIT 2.1.0-beta3
- AerialInfo:
```
Aerial Info
-----------
Filetype: lua
Configured backends:
  treesitter (supported) (attached)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```
- Aerial config:
```lua
-- Call the setup function to change the default behavior
require('aerial').setup({
  -- When you fold code with za, zo, or zc, update the aerial tree as well.
  -- Only works when manage_folds = true
  link_folds_to_tree = true,

  -- Fold code when you open/collapse symbols in the tree.
  -- Only works when manage_folds = true
  link_tree_to_folds = true,

  -- Use symbol tree for folding. Set to true or false to enable/disable
  -- 'auto' will manage folds if your previous foldmethod was 'manual'
  manage_folds = true,
})
```

**To Reproduce**
1. Install aerial and set aerial config to the minimal config provided
2. Open a file (`.c`, `.cpp`, `.lua`, ...) containing function/method definitions
3. Function definitions are folded by aerial automatically

If possible, provide a minimal file that will trigger the issue:
```lua
-- Call the setup function to change the default behavior
require('aerial').setup({
  -- When you fold code with za, zo, or zc, update the aerial tree as well.
  -- Only works when manage_folds = true
  link_folds_to_tree = true,

  -- Fold code when you open/collapse symbols in the tree.
  -- Only works when manage_folds = true
  link_tree_to_folds = true,

  -- Use symbol tree for folding. Set to true or false to enable/disable
  -- 'auto' will manage folds if your previous foldmethod was 'manual'
  manage_folds = true,
})
```

**Screenshots**
![image](https://user-images.githubusercontent.com/76579810/170654253-9ecc3dbd-84f1-4040-a9af-0cc2a4e5d4a2.png)

**Additional context**
Setting `manage_folds` to false solves this problem, but I still want to use aerial to manage folds while not automatically folds the function on entering each file.

**Comment by stevearc** [comment]
Take a look at `:help foldlevelstart` and `:help foldlevel`. I have this in my config for exactly this purpose:
```lua
-- Start with folds open
vim.o.foldlevelstart = 99
vim.o.foldlevel = 99
```

**Comment by Bekaboo** [comment]
> Take a look at `:help foldlevelstart` and `:help foldlevel`. I have this in my config for exactly this purpose:
> 
> ```lua
> -- Start with folds open
> vim.o.foldlevelstart = 99
> vim.o.foldlevel = 99
> ```

Thanks! It works as I expected.
