### ISSUE TITLE
Feature - show parent class(es)

### ISSUE THREAD

**Issue by JoseConseco** [stevearc/aerial.nvim#11]
Hi would it be possible to show parent classes  in aerial?
![image](https://user-images.githubusercontent.com/13521338/128167245-3c66be03-c70d-4ccb-8b37-adf24da3c56c.png)
IMO it could help navigate code faster if we could in addition use  <Enter> to jump into parent definition

**Comment by stevearc** [comment]
Showing the parent class would require a whole lot of specialized code, possibly even per-language as there's no general concept of "find superclass" in the LSP spec. Given the complexity involved, I don't think it's worth it for a relatively minor feature

**Comment by JoseConseco** [comment]
ok, I was thinking  this info may be not available through lps. Still I was wort asking.  I will close this then
