### ISSUE TITLE
`:Telescope aerial` reports error when workspace is not ready

### ISSUE THREAD

**Issue by lixvbnet** [stevearc/aerial.nvim#110]
I have a key binding for command `:Telescope aerial` so can call it quickly.

## Environment:
- gopls (or any other LSP environment)

## Steps:

Open a go file and **immediately** try open telescope aerial window before the workspace is 'ready'.

## Expected behavior:
Shoud be like `AerialToggle` command, which shows "loading..." if workspace is not yet ready, and otherwise shows file outline.

## Actual behavior:
It reports error

```shell
Error executing Lua callback: ...er/opt/aerial.nvim/lua/aerial/backends/lsp/callbacks.lua:14: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_line_count'
        ...er/opt/aerial.nvim/lua/aerial/backends/lsp/callbacks.lua:14: in function 'process_symbols'
        ...er/opt/aerial.nvim/lua/aerial/backends/lsp/callbacks.lua:83: in function 'handle_symbols'
        .../packer/opt/aerial.nvim/lua/aerial/backends/lsp/init.lua:74: in function 'fetch_symbols_sync'
        ...ker/opt/aerial.nvim/lua/telescope/_extensions/aerial.lua:21: in function <...ker/opt/aerial.nvim/lua/telescope/_extensions/aerial.lua:11>
        ...pack/packer/opt/telescope.nvim/lua/telescope/command.lua:193: in function 'run_command'
        ...pack/packer/opt/telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
        ...site/pack/packer/opt/telescope.nvim/plugin/telescope.lua:109: in function <...site/pack/packer/opt/telescope.nvim/plugin/telescope.lua:108>
Press ENTER or type command to continue
```

**Comment by stevearc** [comment]
So that crash is actually just due to a bug, not because the workspace is starting up 😅

I believe I've fixed it, so if you give it another try you should at least get new and interesting errors

**Comment by lixvbnet** [comment]
@stevearc Ohh ok.. I re-tried several times and this issue seems gone. 😄  Thank you for fixing this. It feels great to be able to use aerial with telescope 🥇
