### ISSUE TITLE
[Feature] Automatically toggle of Aerial windows when switching buffers

### ISSUE THREAD

**Issue by pidgeon777** [stevearc/aerial.nvim#128]
Let's imagine a layout with 4 buffers as follows:

![image](https://user-images.githubusercontent.com/13739892/182324916-5a0c2354-8fc9-46b4-9a2a-b09aa1e8ba1d.png)

What I'm trying to achieve, is to automatically open an Aerial window when switching to one of those 4 buffers, in a way such that the aerial window is displayed just at the right (or left) of the selected buffer, without modifying the overall buffer layout.

So, when switching to the orange buffer, Aerial (blue) should be opened and displayed this way:

![image](https://user-images.githubusercontent.com/13739892/182325321-916331b1-f48e-468d-be15-3d28eb200db7.png)

When selecting another buffer (yellow), the previous Aerial window should be closed and opened next to the newly selected buffer:

![image](https://user-images.githubusercontent.com/13739892/182325546-9eabd262-104b-447a-bbba-373c8c764564.png)

How could this behaviour be achieved?

**Comment by stevearc** [comment]
There are already *some* pieces of this in place
```lua
require('aerial').setup({
  -- Open relative to window, not pinned to the far left/right
  placement_editor_edge = false,
  -- Automatically open aerial when you enter a buffer
  open_automatic = true,
})
```

The part that's missing is closing aerial when you leave the window. I'll look into this

**Comment by pidgeon777** [comment]
> The part that's missing is closing aerial when you leave the window. I'll look into this

Thank you 👍

And how should `close_behavior` be configured instead, to obtain the behaviour I described above?

**Comment by pidgeon777** [comment]
Don't worry, we all have our busy schedules, take your time 😉

**Comment by stevearc** [comment]
Quick update: I'm going to be off the grid for about a week. This is been in the pending status for longer than I'd like, but it's still on my todo list and I'll come back to it as soon as I'm able.

**Comment by stevearc** [comment]
Okay, this request led me down a rabbit hole of refactoring config options to make more sense and be more extensible. I've [put up a PR](https://github.com/stevearc/aerial.nvim/pull/144) that should provide you with the options that you want. Could you check it out and see if it's working as expected? The config options you'll want to set are:
```lua
require('aerial').setup({
    close_automatic_events = {
      "unfocus",
    },
    open_automatic = true,
})
```

**Comment by pidgeon777** [comment]
Hello, how could I test your PR 'installing' it with packer? Currently, the latest commit from the main branch gets downloaded with the basic packer config:

```lua
    {
      'stevearc/aerial.nvim',
      config = function()
        require("mine.my-aerial-nvim").config()
      end,
      disable = not lvim.builtin.aerial.active,
    },
```

**Comment by pidgeon777** [comment]
It seems to work ok 👍.

And what should the configuration be if I wanted to do the same as above, but without automatically closing the current buffer symbol panel when unfocusing it?

So that for example, given 4 identical buffers split into 4 window zones, every time I enter one of those zones then the corresponding symbol panel appears next to the buffer, leaving the other symbol panels open.

**Comment by pidgeon777** [comment]
By doing that it works, but if two or more buffers are the same, then the panel is shown only next to the first buffer which gets the focus first.

It is good behaviour which could be useful in some cases, but would there be a way to enable an option to show a panel for each buffer when focused, even if a symbol panel already exists for it?

**Comment by stevearc** [comment]
Needed to do some additional cleanup post-merging that PR. Should be working for you as expected now

**Comment by pidgeon777** [comment]
It works perfectly. Great work! 👍
