### ISSUE TITLE
Open aerial next to the focused window

### ISSUE THREAD

**Issue by shibotto** [stevearc/aerial.nvim#129]
**System information**
- OS: GNU/Linux
- Neovim version: 0.7.2

**Steps to reproduce**
1. Open two or more windows of the same buffer

When not floating, aerial opens either to the left of the first window or to the right of the last one. Take a look at the screenshots (notice the focused window):

![aerial](https://user-images.githubusercontent.com/3816409/182319871-94e63549-a1ef-44b8-9a7e-e21da1c582dc.png)

Would it be possible to always have it spawned next to the focused window, to achieve something like this?

![aerial2](https://user-images.githubusercontent.com/3816409/182346204-34f65d59-5ff3-4c61-a16e-580742b85cc8.png)

**Comment by stevearc** [comment]
Shouldn't be too hard to add support for this, but I'll need to add another config option for it. Will look into it soon

**Comment by stevearc** [comment]
I've refactored some of the options (in a backwards-compatible way). The following should do what you want:
```lua
require('aerial').setup({
  layout = {
    placement = 'window',
  },
})
```

**Comment by shibotto** [comment]
This is simply perfect, thank you very much! ❤️
