### ISSUE TITLE
Aerial float produces error: bad argument #2 to 'aggregator'

### ISSUE THREAD

**Issue by catgoose** [stevearc/aerial.nvim#133]
**Describe the bug**
Aerial tree on left and right works, but float produces the error:

```
E5108: Error executing lua ...site/pack/packer/start/aerial.nvim/lua/aerial/layout.lua:24: bad argument #2 to 'aggregator' (number expected, got nil)
stack traceback:
        [C]: in function 'aggregator'
        ...site/pack/packer/start/aerial.nvim/lua/aerial/layout.lua:24: in function 'calc_list'
        ...site/pack/packer/start/aerial.nvim/lua/aerial/layout.lua:31: in function 'calculate_width'
        ...site/pack/packer/start/aerial.nvim/lua/aerial/window.lua:72: in function 'create_aerial_window'
        ...site/pack/packer/start/aerial.nvim/lua/aerial/window.lua:227: in function 'open'
        ...site/pack/packer/start/aerial.nvim/lua/aerial/window.lua:271: in function 'toggle'
        ...m/site/pack/packer/start/aerial.nvim/lua/aerial/init.lua:84: in function 'toggle'
        [string "luaeval()"]:1: in main chunk
```

**System information**
- Ubuntu
- Neovim version: nightly
- AerialInfo: 
- ```
- Aerial Info
-----------
Filetype: typescript
Configured backends:
  treesitter (supported) (attached)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
``
- Aerial config:
```lua
{
	on_attach = function(bufnr)
		vim.api.nvim_buf_set_keymap(bufnr, "n", "<leader>a", "<cmd>AerialToggle! float<CR>", {})
		vim.api.nvim_buf_set_keymap(bufnr, "n", "H", "<cmd>AerialPrev<CR>", {})
		vim.api.nvim_buf_set_keymap(bufnr, "n", "L", "<cmd>AerialNext<CR>", {})
		vim.api.nvim_buf_set_keymap(bufnr, "n", "<leader>H", "<cmd>AerialPrevUp<CR>", {})
		vim.api.nvim_buf_set_keymap(bufnr, "n", "<leader>L", "<cmd>AerialNextUp<CR>", {})
	end,
}
```

**To Reproduce**
1. AerialToggle produces no error
2. AerialToggle float produces error

If possible, provide a minimal file that will trigger the issue:
```
minimal code here
```

This started happening yesterday.

**Screenshots**
![image](https://user-images.githubusercontent.com/21010072/183083170-19e444fe-6478-45d9-b5f6-e3a47c47fa2e.png)
![image](https://user-images.githubusercontent.com/21010072/183083217-e60de04b-fb45-4e49-a442-fed1d39f7564.png)

**Comment by stevearc** [comment]
Thanks for the report! Should be fixed, and I've added a regression test for this case.
