### ISSUE TITLE
[FEATURE REQ] Single-instance mode

### ISSUE THREAD

**Issue by drinkitup777** [stevearc/aerial.nvim#149]
It would be helpful if aerial could open in single-instance mode, the contents changing whenever the current window changes. Something like a file tree sidebar but for symbols. Would this be possible?

**Comment by stevearc** [comment]
I just landed a refactor of some of the config options in #144. The way to do this now is:

```lua
require('aerial').setup({
  layout = {
    placement = "edge",
  },
  attach_mode = "global",
})
```

**Comment by drinkitup777** [comment]
Tested and working well. Thanks for the quick response.
