### ISSUE TITLE
Bug about listchars

### ISSUE THREAD

**Issue by XXiaoA** [stevearc/aerial.nvim#150]
**Describe the bug**
Listchars of origin window disappear after entering aerial window

**System information**
- OS: linux
- Neovim version: nightly
- AerialInfo: [output of :AerialInfo]
```
Aerial Info
-----------
Filetype: lua
Configured backends:
  lsp (not supported) [LSP client not attached (did you call aerial.on_a
ttach?)]
  treesitter (supported) (attached)
  markdown (not supported) [Filetype is not markdown]
Show symbols: Array, Boolean, Class, Constant, Constructor, Enum, EnumMe
mber, Event, Field, File, Function, Interface, Key, Method, Module, Name
space, Null, Number, Object, Operator, Package, Property, String, Struct
, TypeParameter, Variable

```
- Aerial config:
```lua
require("aerial").setup({}) 
```

**To Reproduce**
1. open nvim
2. run `:AerialOpen`

**Screenshots**

https://user-images.githubusercontent.com/62557596/189872295-bf65d6c7-c6a1-4bc4-8a74-0161ea4ddf61.mp4

**Additional context**
This bug appear after this commit d1e0bcd3458204ffaa8fdf311e97abbcc8ce84b7

**Comment by stevearc** [comment]
I cannot reproduce this. I've tried on v0.7.2 and on nightly. I've tried with my normal config and with a minimal config that consists of only 
```lua
vim.o.list = true
require('aerial').setup({})
```

Could this be caused by some interaction with another plugin you're running? Can you try with a minimal config and see if the issue reproduces?

**Comment by XXiaoA** [comment]
> I cannot reproduce this. I've tried on v0.7.2 and on nightly. I've tried with my normal config and with a minimal config that consists of only
> 
> ```lua
> vim.o.list = true
> require('aerial').setup({})
> ```
> 
> Could this be caused by some interaction with another plugin you're running? Can you try with a minimal config and see if the issue reproduces?

I'll make a minimal configuration ASAP. Unluckily it maybe in next weekend. because I'm gonna go to school tomorrow.
BTW, thx for ur awesome plugin! 😁

**Comment by sdemura** [comment]
I see this too. 

If you open Aerial, change focus and go back to the aerial split, then the visual bug disappears

**Comment by stevearc** [comment]
Still can't get it to repro, but I've switched to using the `list` option instead of `listchars` (which is the more correct way to do what I want anyway). Can you check it again and see if that made a difference?

**Comment by XXiaoA** [comment]
@stevearc  The minimal configuration I tried:
```lua
vim.opt.runtimepath:append("~/repos/aerial.nvim/")
vim.opt.runtimepath:append("~/repos/indent-blankline.nvim/")
vim.opt.runtimepath:append("~/repos/nvim-treesitter")

local o = vim.opt
o.list = true
o.listchars:append("space:⋅")

require('aerial').setup({})
require("indent_blankline").setup({})

for index, valu2.5e in ipairs({}) do
    if index == value then
        print(index)
    end
end
```

This seems that there is conflict between `aerial` and `indent-blankline`

https://user-images.githubusercontent.com/62557596/191955951-7a2b4f27-8bda-473f-a3e7-7f52a625310d.mp4

**Comment by stevearc** [comment]
Thanks for the repro! I was able to narrow down the cause. Something aerial is doing _does_ trigger it, but it's an autocmd + some behavior in indent-blankline that's causing the display issue. I've filed https://github.com/lukas-reineke/indent-blankline.nvim/issues/482 to follow up.

**Comment by stevearc** [comment]
Fixed upstream in version 3 of indent-blankline
