### ISSUE TITLE
Invalid window id error

### ISSUE THREAD

**Issue by jaekyeom** [stevearc/aerial.nvim#152]
**Describe the bug**
I believe this is different from #151 .

**EDIT**: It seems that the error could be a conflict with one of the other plugins.
But I wonder if there is something like `attach_mode = "buffer"`.

**System information**
- OS: linux, mac
- Neovim version: NVIM v0.7.2
- AerialInfo:
```
Aerial Info
-----------
Filetype: python
Configured backends:
  lsp (supported) (attached)
  markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```
- Aerial config:
```lua
    aerial.setup({
        backends = {
            ['_'] = { "lsp", "markdown" },
            ['markdown'] = { "markdown", "lsp" },
        },

        layout = {
            default_direction = "prefer_left",
        },

        default_bindings = true,

        filter_kind = {
            ['markdown'] = {'String'},
        },
    })
```

**To Reproduce**
1. Open Aerial
2. `:vsplit`
3. `:quit` the older window

**Screenshots**

https://user-images.githubusercontent.com/6262727/191050494-61d99d7d-6eaa-4a95-b038-ced96daa2039.mov

**Additional context**

**Comment by stevearc** [comment]
I couldn't repro (as you mentioned, it is likely an interaction with another plugin), but I added some `nvim_win_is_valid` guards that should prevent the error

**Comment by jaekyeom** [comment]
Thanks for the patch, I appreciate your work!
