### ISSUE TITLE
C style struct variable definition in C++ file creates wrong aerial symbols

### ISSUE THREAD

**Issue by ByunghoonKim** [stevearc/aerial.nvim#153]
**Describe the bug**
When C-style struct variable definition is used in C++ file, i.e. with `struct` keyword in front of a structure name,  aerial seems to interpret it as a new structure declaration/definition and add a wrong symbol to the aerial symbols list.

**System information**
- OS: [mac]
- Neovim version:                                                                               
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
```
- AerialInfo: 
```
Aerial Info                                                                                                           
-----------
Filetype: cpp
Configured backends:
  treesitter (supported) (attached)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```
- Aerial config:
```lua
use {'stevearc/aerial.nvim',    -- code outline window
    config = function ()
        local aerial = require 'aerial'
        aerial.setup({})
        vim.keymap.set('n', '<leader>ae', aerial.toggle)
    end
}
```

If possible, provide a minimal file that will trigger the issue:
```
// bug.cpp
struct Point {
    int x;
    int y;
};

void foo()
{
    Point a1;
    struct Point a2;    // C style variable definition causes an aerial error
}

void boo()
{
    Point* pa1 = new Point;
    struct Point* pa2 = new struct Point;   // two aerial errors

    delete pa2;
    delete pa1;
}
```

**Screenshots**
<img width="938" alt="Screen Shot 2022-09-21 at 0 09 18" src="https://user-images.githubusercontent.com/44054076/191298966-d9263094-8b1c-4092-92f2-2743282d6f0c.png">

**Comment by stevearc** [comment]
Thanks for the thorough report with example code! Should be fixed now.

**Comment by ByunghoonKim** [comment]
Thank you for this very helpful plugin. :)
