### ISSUE TITLE
[FEATURE] Support for renaming symbols 

### ISSUE THREAD

**Issue by fgsch** [stevearc/aerial.nvim#156]
It'd be extremely useful if we could rename symbols from the navigation window.

**Comment by stevearc** [comment]
At first I thought this doesn't have a place in aerial, but then I had some ideas. I've prototyped some of the work but it needs more refinement. Nothing is ready yet, but I just wanted to drop a note that I've seen this and have spent some time on it. Can't promise any ETA, but I'll be working on it as time permits.

**Comment by fgsch** [comment]
Awesome! Thanks for the update, much appreciated!

**Comment by stevearc** [comment]
And just one day after giving a vague progress update, I've unfortunately had to discard the idea. I documented my process in the attached PR. Basically: it is technically feasible, but the approach I was taking produced far more complexity than I was comfortable with for this feature.

If you or someone else can come up with a way to implement this without so much complexity, I would happily review a PR, but I won't be picking this back up myself.
