### ISSUE TITLE
[Bug]: cannot configure `filter_kind` properly due to filetype mapping 

### ISSUE THREAD

**Issue by xeluxee** [stevearc/aerial.nvim#158]
**Describe the bug**
I'm using filetype mapping (see `:help aerial-filetype-map`) for `filter_kind`. If I set `_` to false (default setting for filetypes not present in the table) Aerial uses default configuration, the one shown in README with only 8 symbols. But it shouldn't exclude anything because `false` is used to display all symbols.

**System information**
- Aerial config:
```lua
-- Paste your call to require("aerial").setup(...) in here
require('aerial').setup {
  backends = { "lsp", "treesitter", "markdown" },
  filter_kind = {
    ["_"] = false,
    lua = {
      "Enum",
      "Function",
      "Method",
    },
  },
}
```

**To Reproduce**
1. Use provided config
2. Open a file (not a lua one)
3. Notice that `false` setting for `_` is ignored

**Possible fix**
Probably there's a bug at line 311, because `false` and `nil` are equally false conditions:
https://github.com/stevearc/aerial.nvim/blob/6f1b28b549147c2f9e09de16869fcc34cf076253/lua/aerial/config.lua#L311
Substituting line 311 with the following code seems to fix the issue
``` lua
      if option["_"] ~= nil then
        return option["_"]
      end
      return default
```

**Comment by stevearc** [comment]
Thanks for the report! Should be fixed now

**Comment by xeluxee** [comment]
It's fixed indeed, thanks
