### ISSUE TITLE
set 'defualt_selection_index' for telescope picker

### ISSUE THREAD

**Issue by winter233** [stevearc/aerial.nvim#161]
when I use aerial extension for telescope, I find that default selection is always the first one. I think it's better to use symbols under cursor as the default selection.

**Comment by stevearc** [comment]
Good suggestion!

**Comment by Marskey** [comment]
nonnonoo, it's not good suggestion. bother me a lot, i use telescope to search symbol, what i want is the first one, but selecttion is in the bottom or somewhere esle.

**Comment by Marskey** [comment]
how can i disable this feat?

**Comment by Marskey** [comment]
oh, i know how to disabled it.
