### ISSUE TITLE
Support help and man buffers

### ISSUE THREAD

**Issue by adoyle-h** [stevearc/aerial.nvim#164]
Neovim builtin `gO` can open an outline in help and :Man buffers. https://neovim.io/doc/user/various.html#gO . But it looks not good.

Can aerial support help and man buffers?  Currently it shows `Aerial could find no supported backend.`

My config:

```lua
backends = {
	['_'] = { 'lsp', 'treesitter' },
	markdown = { 'markdown' },
},
```

**Comment by stevearc** [comment]
I've added support for help files. Man is trickier because there's no treesitter parser for it, but it should still be possible.

**Comment by stevearc** [comment]
Man page support added

**Comment by adoyle-h** [comment]
It's excellent! Thank you so much. @stevearc
