### ISSUE TITLE
Move cursor to current symbol location when opening Aerial

### ISSUE THREAD

**Issue by axieax** [stevearc/aerial.nvim#165]
Helloo, is it possible to:
1. Move the cursor to the current symbol location on `:AerialToggle` and
2. Center the Aerial buffer so that the cursor is in the middle of the buffer.

**Comment by axieax** [comment]
Sounds good, thanks for updates :))

**Comment by stevearc** [comment]
Merged in the large refactor, which includes the centering logic!

**Comment by kevmuko** [comment]
@stevearc, I'm frequently seeing this error after this recent change:

```
Error executing vim.schedule lua callback: ...site/pack/packer/start/aerial.nvim/lua/aerial/window.lua:59: attempt to index local 'last_position' (a nil value)
stack traceback:
        ...site/pack/packer/start/aerial.nvim/lua/aerial/window.lua:59: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Any idea why this might be happening?

**Comment by kevmuko** [comment]
For context, I have a pretty simple config:
```
aerial.setup({
  layout = {
    min_width = 28,
  },
  attach_mode = 'global',
  lazy_load = false,
  open_automatic = true,
  show_guides = true,
})
```

**Comment by stevearc** [comment]
Needed more guards for invalid values, and needed to account for more symbol backend latency. Should be fixed now
