### ISSUE TITLE
keymap.set in on_attach function is always called when buffer entered

### ISSUE THREAD

**Issue by adoyle-h** [stevearc/aerial.nvim#166]
**Describe the bug**

Set buffer keymap in on_attach function will affect all buffers.

**To Reproduce**

```
require('aerial').setup({
  on_attach = function(bufnr)
    local aerial = require('aerial')
    require('notify')(string.format('buffer: %s', bufnr)) -- If notify not installed, use `print`

    -- vim.keymap.set('n', '<C-k>', function()
    -- 	aerial.up(-1)
    -- end, { buffer = bufnr })
    --
    -- vim.keymap.set('n', '<C-j>', function()
    -- 	aerial.up(1)
    -- end, { buffer = bufnr })
  end,
})
```

**Screenshots**

<img width="426" alt="CleanShot 2022-10-20 at 18 14 51@2x" src="https://user-images.githubusercontent.com/1998490/196922148-b3b9ed11-9d53-4d26-be24-13fae9726c90.png">

**What to be expected**

Only call `on_attach` after aerial window opened.

Set buffer keymap in on_attach function will only affect aerial buffer.

**Comment by stevearc** [comment]
Hmmm...perhaps this is a wording issue in the documentation. The `on_attach` function is called only for the _source_ buffer, not the _aerial_ buffer. It's intended to make it easy to set up keymaps for interacting with aerial once aerial has found a backend and attached to the buffer. If you want to set keymaps for aerial specifically, I'd recommend using a [ftplugin/aerial.lua](https://github.com/stevearc/aerial.nvim#default-keybindings) file, or by simply creating a FileType autocmd.

I may make it easier to change bindings in the aerial window in the future.

**Comment by adoyle-h** [comment]
I see. Thank you.

**Comment by adoyle-h** [comment]
@stevearc I have disabled all plugins but aerial. And set below codes.

```lua
vim.api.nvim_create_autocmd('FileType', {
	callback = function(args)
		if (args.match == 'aerial') then print('====', vim.loop.now()) end
	end,
})
```

I find that the `FileType` autocmd is triggered when aerial window opened and cursor moved out aerial window.
But I expected it to print time only when aerial window opened. Is it a bug?

**Comment by stevearc** [comment]
Not strictly a bug, since the work it's doing should be idempotent, but unnecessary. I've pushed up a change that should prevent the duplicate calls.

Also, you can now set aerial-buffer keymaps in the call to `setup()`. Check the "keymaps" option.
