### ISSUE TITLE
Telescope Extension Default Sort Order (sorting_strategy)

### ISSUE THREAD

**Issue by zach-is-my-name** [stevearc/aerial.nvim#169]
### Question or Feature Request

I'd like the Telescope extension to be sorted by default in descending order (the first symbol of the file appears at the top of the picker in row 1... and so on) 

Is this possible (either now or in a future version)?
Thanks! Great Extension!

My config: 

```
lua <<EOF
require('telescope').setup{
...
extensions = {
  aerial = {
   sorting_strategy="descending" 
    }
  }
}
EOF
```

Linux
Neovim 0.7.0
Aerial Info
-----------
Filetype: javascript
Configured backends:
  lsp (supported) (attached)
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct

 require("aerial").setup({
   max_width = {50, .25},
   backends = {"lsp"},
...

**Comment by stevearc** [comment]
I've added a fix for this is the giant refactor PR I've been working on (would have produced merge conflicts otherwise). Hoping to land it in the next couple days.

**Comment by stevearc** [comment]
Merged!
