### ISSUE TITLE
Aerial with tsitter - constantly opens qfix list - after any character press

### ISSUE THREAD

**Issue by JoseConseco** [stevearc/aerial.nvim#17]
**Describe the bug**
After disabling `require'aerial'.on_attach(client) - outliner` in lsp, and restarting aerial it should use telescope - and it works. Except after switching buffer, aerial will now constantly open qfix list when going into insert mode and typing any characters like seen below:

![AeiralQfixPopup](https://user-images.githubusercontent.com/13521338/142996527-5d431675-1940-4a0b-ad59-9a75220d72f8.gif)
This makes it impossible to work. 
**System information**
- OS: [linux]
- Neovim version:
- NVIM v0.6.0-dev+594-g36538417f
Build type: Debug
LuaJIT 2.1.0-beta3

- AerialInfo: [output of :AerialInfo]
![image](https://user-images.githubusercontent.com/13521338/142996751-eb7c6d20-48b0-40c0-9091-a1cf5567e786.png)

**To Reproduce**
1. Disable aerial lsp. And restart nvim
2. Open any project - editing first buffer works ok. Aerial works ok too
3. open other file (:e some.file.py) - now aerial will constantly open qfix window. Opening aerial itself gives error:
![image](https://user-images.githubusercontent.com/13521338/142996998-0a104c30-9c8a-459c-b28f-37cbbfaf4d77.png)

**Additional context**
Works ok on lsp.

**Comment by olimorris** [comment]
Can confirm this is happening for myself too

**Comment by stevearc** [comment]
Thanks for the report! I tracked the issue down. It's due to the fact that the LSP hook was removed, but the `backends` option still contains the 'lsp' string so Aerial was still trying to use LSP document symbols. The built-in neovim handler for document symbols opens up the quickfix, which was why you were seeing the quickfix.

I added a fix that will prevent the LSP from attempting to do anything if the on_attach callback isn't called.

**Comment by JoseConseco** [comment]
while auto popup of quick fix list is gone, the error when opening Aerial on second opened buffer is till there:
![image](https://user-images.githubusercontent.com/13521338/143077176-6e0e6fd7-20c8-4303-915e-62e81d82467f.png)

**Comment by stevearc** [comment]
Apologies! I skimmed over that part of the initial bug report. Should actually be fixed now.

**Comment by JoseConseco** [comment]
thanks. Now it works great.
