### ISSUE TITLE
lazy loading

### ISSUE THREAD

**Issue by mathjiajia** [stevearc/aerial.nvim#173]
**Describe the bug**
When using lazy loading (by default),
`aerial` will not fallback to `lsp` if `treesitter` is not support.

**System information**
- OS: [mac]
- Neovim version: NVIM v0.9.0-dev-169+gfef8ff908
- AerialInfo: [
Filetype: tex
Configured backends:
  treesitter (not supported) [No query file for 'latex']
  lsp (not supported) [LSP client available, but not attached]
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: Class, Constant, Constructor, Enum, EnumMember, Function, Interface, Method, Module, Object, Struct, Variable]
- Aerial config:
```lua
require('aerial').setup({
	filter_kind = {
		'Class', 'Constant', 'Constructor', 'Enum',
		'EnumMember', 'Function', 'Interface', 'Method',
		'Module', 'Object', 'Struct', 'Variable',
	},
	-- lazy_load = false,
	show_guides = true,
})
```

**To Reproduce**
1. Open a file that haven't been supported by treesitter, say `tex`
2. Use `AerialToggle`
3. 

If possible, provide a minimal file that will trigger the issue:
```
minimal code here
```

**Screenshots**
<img width="1546" alt="Screenshot 2022-10-27 at 8 27 30 AM" src="https://user-images.githubusercontent.com/35106942/198163942-7eefe3d2-4b59-478a-9770-de53cb3182c5.png">

**Additional context**
Maybe you can call `create_autocmds()` in the lazy mode??

**Comment by rebelot** [comment]
To me, aerial does not attach to lsp if lazy_mode is true, unless I reload the buffer.

this is my workaround

```lua
    use({
        "stevearc/aerial.nvim",
        event = "BufRead",
        cmd = { "AerialToggle", "AerialInfo" },
        keys = { { "n", "<leader>at" } },
        config = function()
            require("aerial").setup({
                lazy_load = false,
                ...
            })
        end
    })
```

**Comment by stevearc** [comment]
This was because we were relying too much on the `LspAttach` autocmd, and that isn't set up when aerial is in lazy (pending loading) mode. I've refactored it to not lean so much on the autocmd, and it should be fixed now.

**Comment by mathjiajia** [comment]
It resolves this problem.
Thank you.
