### ISSUE TITLE
Folding not working properly in markdown

### ISSUE THREAD

**Issue by vishalbalaji** [stevearc/aerial.nvim#178]
**Describe the bug**
In markdown, level-1 headers fold under the previous header instead of as individual sections.

**System information**
- OS: linux
- Neovim version: 0.9.0-dev-155+g771824128
- AerialInfo:

```
Aerial Info
-----------
Filetype: markdown
Configured backends:
  treesitter (supported) (attached)
  lsp (not supported) [No LSP client found]
  markdown (supported)
  man (not supported) [Filetype is not man]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```
- Aerial config:
```lua
require("aerial").setup({
  link_tree_to_folds = false,
  link_folds_to_tree = false,
  manage_folds = false,
  layout = {
    width = 0.2,
    max_width = { 30 },
  },
})
vim.api.nvim_set_keymap("n", "<Tab>", "za", { noremap = false, silent = true })
vim.api.nvim_set_keymap("n", "<S-Tab>", "zA", { noremap = false, silent = true })
```

**To Reproduce**
1. Set  foldexpr to `nvim_treesitter#foldexpr()`
2. Close all folds uring `zM` or just the first fold using `za`

If possible, provide a minimal file that will trigger the issue:
```
minimal code here
```
**Screenshots**

**All folds open**

![tmp_scrot](https://user-images.githubusercontent.com/36506250/198876339-1de3f4d2-4f00-45bc-99e4-4165c9e34d83.png)

**All folds collapsed under the first header on `zM`**

![2022-10-30_17:05:03_scrot](https://user-images.githubusercontent.com/36506250/198876373-eae178f4-26b0-4e19-b523-b03cdb7a7ff6.png)

**Additional context**

**Comment by stevearc** [comment]
Thanks for the report! Should be fixed now.

**Comment by vishalbalaji** [comment]
Yep, fixed after the update. Thanks!
