### ISSUE TITLE
Mapping `<` and `>`

### ISSUE THREAD

**Issue by axieax** [stevearc/aerial.nvim#179]
**Describe the bug**

Hi again!! I'm trying to map `<` and `>` for decreasing and increasing the fold level in the aerial buffer respectively. However, there is a delay due to the built-in `<<` and `>>` mapping. Mapping those to `<Nop>` globally seems to resolve the issue, but not on the buffer only for some reason. Do you know if there is a way to remove the delay on these keys (since nvim waits to check the next key press). 

**System information**
- OS: Mac
- Neovim version: 0.8
- AerialInfo: [output of :AerialInfo]
- Aerial config:
```lua
-- Paste your call to require("aerial").setup({
  keymaps = {
    ["<"] = "actions.tree_decrease_fold_level",
    [">"] = "actions.tree_increase_fold_level",
  },
})
```

**To Reproduce**
1. Open Aerial buffer
2. Press `<` to decrease fold level
3. There is a delay

If possible, provide a minimal file that will trigger the issue:
```
minimal code here
```

**Screenshots**

**Additional context**

**Comment by stevearc** [comment]
I wasn't able to reproduce the issue with my config; the `<` and `>` keys respond instantly. I also tried with a minimal config and couldn't repro:

```lua
local install_path = vim.fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
local is_bootstrap = false
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  is_bootstrap = true
  vim.fn.execute("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
  vim.cmd([[packadd packer.nvim]])
end

require("packer").startup(function(use)
  use("wbthomason/packer.nvim")
  use("stevearc/aerial.nvim")
  use("nvim-treesitter/nvim-treesitter")
  if is_bootstrap then
    require("packer").sync()
  end
end)

if is_bootstrap then
  print("==================================")
  print("    Plugins are being installed")
  print("    Wait until Packer completes,")
  print("       then restart nvim")
  print("==================================")
  return
end

vim.g.mapleader = " "
vim.g.maplocalleader = " "

require("nvim-treesitter.configs").setup({
  ensure_installed = { "markdown", "markdown_inline" },

  highlight = { enable = true },
  indent = { enable = true },
})

require("aerial").setup({
  keymaps = {
    ["<"] = "actions.tree_decrease_fold_level",
    [">"] = "actions.tree_increase_fold_level",
  },
})
vim.keymap.set("n", "<leader>a", "<CMD>AerialToggle<CR>")
```

Do you have some other plugin or something that has globally mapped `<<`/`>>`? What's the output of `:nmap <`?

**Comment by axieax** [comment]
It seems that vim-unimpaired, which-key and stay-in-place.nvim all cause this to happen. Is there a way to remove the delay? I know neo-tree.nvim does it with their `<` and `>` mappings.

```
   >           *@<Lua 811: ~/.local/share/nvim/site/pack/packer/opt/aerial.nvim/lua/aerial/actions.lua:122>
                 Increase the fold level of the tree
n  >iÞ         * <Nop>
n  >aÞ         * <Nop>
n  >Þ          * <Nop>
n  >p            <Plug>(unimpaired-put-below-rightward)
n  >P            <Plug>(unimpaired-put-above-rightward)
n  >s<Esc>     & <Nop>
n  >s            <Plug>(unimpaired-disable)
n  >>          * <Lua 157: ~/.local/share/nvim/site/pack/packer/start/stay-in-place.nvim/lua/stay-in-place.lua:42>
n  >           * <Cmd>lua require("which-key").show(">", {mode = "n", auto = true})<CR>
```

**Comment by stevearc** [comment]
If you set `nowait = true` and you don't have any other buffer-local mappings that involve `<`/`>`, that should remove the delay. There's no affordance for doing this with the `keymaps` key of the aerial setup config, as that's intended just to make very simple configuration easier. You'll need to set up an autocmd or similar:

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "aerial",
  desc = "Set aerial keymaps",
  callback = function(args)
    vim.keymap.set(
      "n",
      "<",
      require("aerial.actions").tree_decrease_fold_level.callback,
      { nowait = true, buffer = args.buf }
    )
    vim.keymap.set(
      "n",
      ">",
      require("aerial.actions").tree_increase_fold_level.callback,
      { nowait = true, buffer = args.buf }
    )
  end,
})
```
See `:help map-nowait` for more details

**Comment by axieax** [comment]
That seems to work thanks! Any possibility of adding this option to a table under mappings for actions (maybe allowing users to specify any options to be passed in for keymaps, other than just desc)?

**Comment by stevearc** [comment]
Sure, you should now be able to use
```lua
require("aerial").setup({
  keymaps = {
      ["<"] = {
        callback = function()
          require("aerial").tree_decrease_fold_level()
        end,
        nowait = true,
      },
  }
})
```

**Comment by axieax** [comment]
Amazing! Thanks again <3
