### ISSUE TITLE
can't recognize any member function defined outside the class definition, such as: void A::bar() {}

### ISSUE THREAD

**Issue by GPN211314** [stevearc/aerial.nvim#18]
**Language**: cpp
**AerialInfo**:
-----------
Filetype: cpp
Configured backends:
  lsp (not supported)
  treesitter (supported) (attached)
  markdown (not supported)
Show symbols: Class, Constructor, Enum, Function, Interface, Method, Struct

The minimal amount of code that demonstrates the missing symbol:
```
void A::bar() {}
```

**Expected symbol**: bar or A::bar

**Comment by stevearc** [comment]
Thanks for the report! Made it super easy to add the missing case.
