### ISSUE TITLE
golang no Interface types

### ISSUE THREAD

**Issue by blob42** [stevearc/aerial.nvim#180]
**Language**: [go]
**AerialInfo**: 
```
Filetype: go
Configured backends:
  treesitter (supported) (attached)
  lsp (not supported) [LSP client not attached (did you call aerial.on_attach?)]
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct

```

The minimal amount of code that demonstrates the missing symbol:
```
type TreeSitter interface {
    Sitter
}
```
Should at least show the `TreeSitter` interface

**Expected symbol**: Interface (TreeSitter)

I tried adding my custom query in `after/queries/go/aerial.scm` with the following, is there a quick guide on how to add our custom queries/enhance aerial ? It would help others add PRs:
```
(type_declaration
  (type_spec
    name: (type_identifier) @name
    type: (interface_type) @??
    ))

```

**Comment by stevearc** [comment]
Oh wow I can't believe I forgot to add a query for interfaces! I've added it now.

You're right though, I probably should add some docs about how to add queries.

**Comment by blob42** [comment]
Thanks a lot it works now, plus I have your patch as a reference documentation 😄
