### ISSUE TITLE
[Comparison] `Symbols-Outline` Vs `Aerial`

### ISSUE THREAD

**Issue by pidgeon777** [stevearc/aerial.nvim#182]
Here is a difference between `Symbols-Outline` plugin and `Aerial` when navigating the same LUA buffer.

`Symbols-Outline`:

![image](https://user-images.githubusercontent.com/13739892/200846340-267d636a-9e06-4211-9e95-6e6c12c1f4d3.png)

`Aerial`:

![image](https://user-images.githubusercontent.com/13739892/200846494-e3fc0847-a78f-4b17-b3de-182238d1ca37.png)

As you can see, code navigation is much more well-presented in `Symbols-Online`.

Given that both plugins have access to the LSP output information, I would like to ask if it is planned to improve the symbols panel by providing a complete user interface such as the one offered by `Symbols-Outline`. Given that `Aerial` is already a great plugin, but missing some details like that, though.

**Comment by pidgeon777** [comment]
My fault, for somewhat reason at first not every LUA symbol was shown with `Aerial`, but with a symbols `filter` option properly set to false for LUA, now everything is much better:

![image](https://user-images.githubusercontent.com/13739892/200849874-f03bab9e-8ac3-46f6-9902-972022d26ae0.png)

Still, as a suggestion, I would add an option to `Aerial` to behave as `Symbols-Outline`, so that a highlight will be applied also to the parent nodes of the currently focused symbols, and not just only on the symbol itself.

These symbol + parent node highlights could be applied both to the buffer and to the symbols panel, still, as an option.

See `Symbols-Outline` and its yellow highlight as a reference in the screenshot I posted, a highlight applied to the symbol and to its parent nodes.

**Comment by pidgeon777** [comment]
Another thing I noted, is that the guide characters are wrongly displayed in _italics_.

I wonder how it could be possible given that this is my configuration:

```lua
    guides = {
      -- When the child item has a sibling below it
      mid_item = "├─",
      -- When the child item is the last in the list
      last_item = "└─",
      -- When there are nested child guides to the right
      nested_top = "│",
      -- Raw indentation
      whitespace = "  ",
    },
```

**Comment by stevearc** [comment]
By default `AerialGuide` was linking to the `Comment` highlight group. If your `Comment` highlight is italic, then `AerialGuide` will be too. I've changed it to just extract the colors from the `Comment` group.

As for highlighting parent symbols when a child is focused, I'll put it on the backlog.

**Comment by Bekaboo** [comment]
> My fault, for somewhat reason at first not every LUA symbol was shown with `Aerial`, but with a symbols `filter` option properly set to false for LUA, now everything is much better

Can you paste your config here? After setting `filter_kind` to `false`, aerial still only gives function symbols...

**Comment by stevearc** [comment]
@Bekaboo you're probably using the treesitter backend. I've only added queries for lua functions, so that's all that will show up. If you use the LSP backend it should show everything.

**Comment by stevearc** [comment]
If you're experiencing performance problems, please open an issue with:
- The language
- The size of the file
- Some example content (doesn't have to be the full file content, just an idea of what sort of structures are used)
- The aerial backend being used
- Detailed description of what behavior you see and when it occurs. For example, "aerial.nvim freezes for a few seconds" is ambiguous. I'm looking for something like "Neovim freezes for a few seconds when I run :AerialToggle" or "aerial.nvim shows a loading spinner for a few seconds after :AerialOpen"

**Comment by towry** [comment]
![截屏2023-07-15 23 43 02](https://github.com/stevearc/aerial.nvim/assets/8279858/a261ea42-d91e-4705-afe4-93ca195adc07)

aerial(left) vs symbols-outline

**Comment by stevearc** [comment]
@towry if you want to see the same symbols as symbols-outline, use the lsp backend and set `filter_kind = false`. I agree that the anonymous functions are low value so I'll be removing those from the treesitter backend.

I'm closing this issue because it is not productive. Bugs or feature requests can be filed as new issues.

**Comment by samarth-nagar** [comment]
@pidgeon777  I cant see anything inside ant function 
![image](https://github.com/stevearc/aerial.nvim/assets/110125971/7ad044d9-cbe2-49bd-8b95-b9b9869f6cf7)
mine look like this even when theres like 5 symbols inside of the time function
