### ISSUE TITLE
Duplicate windows with open_automatic = true & attach_mode = global 

### ISSUE THREAD

**Issue by kevmuko** [stevearc/aerial.nvim#185]
**Describe the bug**
If you split a window with open_automatic = true & attach_mode = global, then you end up with two Aerial windows that mirror the same content. There probably needs to be a simple check to not create another Aerial view if there's already an existing one.

**System information**
- OS: [windows/linux/mac]
- Neovim version:
- AerialInfo: [output of :AerialInfo]
- Aerial config:
```lua
-- Paste your call to require("aerial").setup(...) in here
```

**To Reproduce**
1. 
2.
3. 

If possible, provide a minimal file that will trigger the issue:
```
minimal code here
```

**Screenshots**

**Additional context**

**Comment by stevearc** [comment]
Thanks for the report! This should be fixed now

**Comment by kevmuko** [comment]
Thanks @stevearc for taking a look at this. When an unsupported buffer is open, I'm seeing that there is almost an infinite loop with the window opening and then closing.

**Comment by stevearc** [comment]
Ah, this was an unfortunate interaction with another change I made recently. That should be resolved now as well
