### ISSUE TITLE
close_on_select not applied to split jumps

### ISSUE THREAD

**Issue by petobens** [stevearc/aerial.nvim#191]
Hi! If I set `close_on_select = true,` and either use the `C-v` or `C-s` maps then the aerial buffer doesn't close upon selection (while when pressing `<CR>` it does close). I would expect all these three to work the same.
Thanks in advance!

**Comment by stevearc** [comment]
I agree, it makes sense for those to function the same. Should be working as expected now!

**Comment by petobens** [comment]
Great. Thanks!
