### ISSUE TITLE
Aerail show_guides desn't work in golang

### ISSUE THREAD

**Issue by 3Xpl0it3r** [stevearc/aerial.nvim#194]
**Describe the bug**
When I trigger aerial in golang, "show_guide" config may doesn't work

**System information**
- OS: [windows/linux/mac]
- Neovim version:
```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Big-Sur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```
- AerialInfo: [output of :AerialInfo]
```
Aerial Info
-----------
Filetype: lua
Configured backends:
  treesitter (supported)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```
- Aerial config:
```lua
                show_guides = true,

                -- Customize the characters used when show_guides = true
                guides = {
                        -- When the child item has a sibling below it
                        mid_item = "├─",
                        -- When the child item is the last in the list
                        last_item = "└─",
                        -- When there are nested child guides to the right
                        nested_top = "│ ",
                        -- Raw indentation
                        whitespace = "  ",
                },

```

**To Reproduce**
1. 
2.
3. 

If possible, provide a minimal file that will trigger the issue:
```
AerialOpen
```

**Screenshots**
<img width="441" alt="image" src="https://user-images.githubusercontent.com/62287907/208219913-c2380216-383b-4097-8165-c1943fba2612.png">

**Additional context**

**Comment by stevearc** [comment]
That's a byproduct of the structure of Go code. It's very flat; not much nesting. If there's no nesting, then there's no guides.

**Comment by 3Xpl0it3r** [comment]
@stevearc 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/62287907/208225086-dec24902-bb87-4e93-94bc-07f5219eb9a5.png">

Is aerial can support display methods of receiver like the picture in golang?

**Comment by stevearc** [comment]
done
