### ISSUE TITLE
Change highlighting of current function

### ISSUE THREAD

**Issue by AlexSWall** [stevearc/aerial.nvim#196]
Is there a way to change the highlight colour/group of the function name in the aerial view for the position the cursor in the main buffer is in?

Currently it appears to be based on the search/match highlighting colour.

For example, if I search `<Anonymous>` and my cursor is at `M.setup_auto_install` in the other window, the colours are the same.

<img width="221" alt="Screenshot 2022-12-23 at 13 01 32" src="https://user-images.githubusercontent.com/31999802/209340494-b1b5b715-bef0-4eda-b3d1-a493bbc185e1.png">

Edit: Obviously this isn't a bug, but I couldn't see how to simply ask a question.

**Comment by stevearc** [comment]
Yes, I believe what you're looking for is the `AerialLine` group, and also perhaps the `AerialLineNC` group. See https://github.com/stevearc/aerial.nvim/#highlight

**Comment by AlexSWall** [comment]
Perfect, thank you, and apologies, I did see that section but my skim of it was insufficient.
