### ISSUE TITLE
Possibility to change Telescope's picker theme

### ISSUE THREAD

**Issue by mrded** [stevearc/aerial.nvim#197]
I'd like to change `:Telescope aerial` to be a dropdown without a preview.

Normally, with Telescope I would do `builtin.find_files(themes.get_dropdown({ previewer = false }))`, but here with only Vim command I cannot find a way to apply theme setting to the picker.

Or, I can do it with settings
```
require('telescope').setup{
  pickers = {
    find_files = {
      theme = "dropdown",
      previewer = false
    }
  }
}
```

Can you please show me how to do that? 

Thanks.

**Comment by stevearc** [comment]
Try this:
```lua
require('telescope').extensions.aerial.aerial(require('telescope.themes').get_dropdown({previewer = false}))
```

**Comment by mrded** [comment]
That works perfectly, thanks!

I think it will make sense to add it to the documentation.
