### ISSUE TITLE
unknow option 'splitkeep' in neovim 0.8.2

### ISSUE THREAD

**Issue by y1rn** [stevearc/aerial.nvim#202]
**Describe the bug**
show `unknow option 'splitkeep'` error.

**System information**
- OS: linux
- Neovim version: 0.8.2
- Aerial config: 
```lua
require("aerial").setup {}
```

**To Reproduce**
 while jumping to declaration.

**Screenshots**

**Additional context**

need to change splitkeep option checking from:
``` 
if vim.o.splitkeep and vim.o.splitkeep ~= "cursor" then
```
to
```
 if vim.fn.exists('&splitkeep') == 1 and vim.o.splitkeep ~= "cursor"
```

**Comment by prgres** [comment]
Same happens to me and above solution works

**Comment by stevearc** [comment]
Thanks for the report! Fixed and regression tests added.
