### ISSUE TITLE
bug: open_automatic = true and attach_mode = 'global' creates 

### ISSUE THREAD

**Issue by kevmuko** [stevearc/aerial.nvim#204]
### Neovim version (nvim -v)

0.8.1

### Operating system/version

Win11

### Output of :AerialInfo

Aerial Info
-----------
Filetype: lua
Configured backends:
  lsp (supported) (attached)
  treesitter (supported)
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: Array, Boolean, Class, Constant, Constructor, Enum, EnumMember, Event, Field, File, Function, Interface, Key, Method, Module, Namespace, Null, Number, Object, Operator, Package, Property, String, Struct, TypeParameter, Variable

### Describe the bug

`open_automatic = true` and `attach_mode = global` seems to open an additional view when opening help windows (`:help <...>`) when a view is already open.

### Steps To Reproduce

1. Run any `:help` command

### Expected Behavior

 I think we'd expect to see the existing window to just update instead of opening another instance of aerial.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/aerial.nvim",
    config = function()
      require("aerial").setup({
        -- add your aerial config here
      })
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "c", "lua" },
        auto_install = true,
        highlight = { enable = true },
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
This required a fairly significant change in how the "ignore" config option works, but though the behavior had to change, I think it should now produce more consistent results. I was never quite able to reproduce your issue with `open_automatic`, but the issue should be fixed now.

**Comment by kevmuko** [comment]
Seems like it works! Thanks for the fix :)
