### ISSUE TITLE
[golang] The methods of a struct can be a subtree of the struct ?

### ISSUE THREAD

**Issue by tenfyzhong** [stevearc/aerial.nvim#206]
<img width="1784" alt="image" src="https://user-images.githubusercontent.com/5044825/212542962-11f79857-a103-4492-8caf-d5155cf6f378.png">

A method is a root node, but it should be a subtree of the struct it belongs to.

**Comment by stevearc** [comment]
There has been more discussion of this in #81, but the summary is:
- Golang is somewhat unique among languages in that the structural layout of the code does not match the hierarchical layout of the concepts. Methods are not nested under structs, and indeed are not guaranteed to be defined below the struct or even in the same file.
- Aerial was built with the assumption that the hierarchical structure _matches_ the code structure
- Making aerial represent the hierarchical structure of Go would require a lot of custom code, and would still be janky. Some of aerial's features would straight up not work, or would have unexpected results.

If this is something you need, you'll have to use a golang-specific plugin.
