### ISSUE TITLE
bug:  invalid buffer id when opening file with keymap

### ISSUE THREAD

**Issue by petobens** [stevearc/aerial.nvim#207]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-771+g18fb669b9b

### Operating system/version

Arch Linux

### Output of :AerialInfo

```
Aerial Info
-----------
Filetype: lua
Configured backends:
  treesitter (supported) (attached)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```

### Describe the bug

I'm getting the error above when opening a file
```
Error executing vim.schedule lua callback: ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:83: Invalid buffer id: 89
stack traceback:
        [C]: in function 'nvim_buf_set_var'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:83: in function 'set_backend'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:100: in function 'attach'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:218: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps To Reproduce

I cannot reproduce this with a minimal init.lua or consistently but essentially:

1. Open some file with a keymap bookmark (in my case I'm using `,es` to open the corresponding markdown lua snippet file)
```lua
u.keymap('n', '<Leader>es', function()
    local snippet_file = vim.bo.filetype .. '.lua'
    if vim.bo.filetype == 'tex' or vim.bo.filetype == 'lua' then
        snippet_file = vim.bo.filetype .. '/' .. snippet_file
    end
    local split = 'split '
    ---@diagnostic disable-next-line: undefined-field
    if vim.fn.winwidth(0) > 2 * (vim.go.textwidth or 80) then
        split = 'vsplit '
    end
    vim.cmd(split .. snippets_dir .. snippet_file)
end)
```
2.  Aerial gives the error above.

### Expected Behavior

No error upon opening the file.

### Additional context

![aerial](https://user-images.githubusercontent.com/2583971/213921537-3d55df0b-7401-4058-b05b-5f493de5b9f8.gif)

**Comment by stevearc** [comment]
That's odd...from the abridged stacktrace it looks like this is coming from the LSP on_attach event. Not sure why this would be producing an invalid buffer, that usually means something is getting deleted right after it's created. I added a guard which should silence the error. Let me know if there are any behavior issues that appear as a result.

**Comment by petobens** [comment]
Seems to work as expected now. Thanks!
