### ISSUE TITLE
Expose current symbol via API

### ISSUE THREAD

**Issue by ikalnytskyi** [stevearc/aerial.nvim#22]
It would be nice to expose current symbol via API, so it can be used and shown in status line. Since aerial.nvim already deals with symbols, it seems just reasonable to expose this information so it can be used by third party plugins. It'd be nice to return some sort of AST, e.g.:

```lua
{
   { lsp_kind = "Class",  name = "MyClass" },  -- maybe the default `icon` should be returned too :thinking: 
   { lsp_kind = "Method", name = "foobar" },
   { lsp_kind = "Variable", name = "myvar" },
}
```

* The nodes returned are only those that weren't filtered out by aerial.nvim (i.e. `filter_kind` is respected)
* How to format the end line is up to user. Some may want to show only the method name, others -- the full path.

---

There are plugins out there that provide similar functionality and have their own drawbacks.

* [liuchengxu/vista.vim](https://github.com/liuchengxu/vista.vim#show-the-nearest-methodfunction-in-the-statusline)
  * Does not support `treesitter`. It's either LSP or ctags or custom providers.
  * Returns only function or method.
  * Does not expose information about parent nodes.
* [SmiteshP/nvim-gps](https://github.com/SmiteshP/nvim-gps)
  * Does not provide enough flexibility on how to render the line.
  * Does nothing useful except for the status line formatting.  

---

**Comment by stevearc** [comment]
I like the idea and it's easy to implement. Thanks!

**Comment by ikalnytskyi** [comment]
Awesome! It works like a charm. Thank you very much. :+1:

**Comment by ikalnytskyi** [comment]
@stevearc I'm interested in writing a https://github.com/nvim-lualine/lualine.nvim component to render current location, and so I wonder, would you be interested to host that plugin in `aerial.nvim`? Somewhere in `lua/lualine/*`, just like you host a telescope extension? Or should I proceed with creating my own repo.

**Comment by stevearc** [comment]
I would be happy to host a lualine extension!

**Comment by ikalnytskyi** [comment]
Great. I'll submit a PR in next day or too.
