### ISSUE TITLE
[Feature] LSP Blacklist

### ISSUE THREAD

**Issue by pidgeon777** [stevearc/aerial.nvim#222]
Sometimes multiple LSPs can be attached to a buffer, and two or more of them could offer the `documentSymbol` capability.

It would be great to add an option to blacklist one or more LSP so that the `documentSymbols` request only goes to the wished server.

**Comment by stevearc** [comment]
I've added a priority ranking for LSP clients. You can set some to be preferred, not preferred, or disable them entirely

**Comment by pidgeon777** [comment]
Great! I'm going to test it right now 👍.

Let's suppose `LSP B` has a lower priority than `LSP A`. What if `LSP B` is started first and then `LSP A`? Will `Aerial` automatically detach from `LSP B` and attach to `LSP A`?

**Comment by stevearc** [comment]
I didn't test exactly that workflow, but I wouldn't say that it "detaches" from `LSP B`. The only concept of attach/detach is for the LSP backend as a whole. What would happen is once `LSP A` attaches it will now be the one that handles all subsequent `documentSymbol` requests. Additionally, if you are using the defaults, once `LSP A` attaches it will probably publish diagnostics, at which point we will refetch the symbols.
