### ISSUE TITLE
Add option for open aerial in floating window

### ISSUE THREAD

**Issue by JoseConseco** [stevearc/aerial.nvim#23]
I wish aerial could open in floating window - somewhere close to current cursor position. 
This way user eyes wont have to travel so far away from current coding position. 
From this:
![image](https://user-images.githubusercontent.com/13521338/143841380-1c854f5c-47e5-4022-a1ff-1d1672a3e651.png)

to somthing like this:
![image](https://user-images.githubusercontent.com/13521338/143841651-c248da93-9afd-437f-b71c-bb0839dd035e.png)

**Comment by stevearc** [comment]
Added! Let me know if you encounter any issues. Try it out with `:AerialOpen float` or by setting `default_direction = 'float'`

**Comment by JoseConseco** [comment]
You implemented it way faster than I expected and It works great. Thanks!
