### ISSUE TITLE
What is the equivalent of require('aerial').setup({}) in you have a init.vim (no Lua) config

### ISSUE THREAD

**Issue by stephane-archer** [stevearc/aerial.nvim#231]
### Neovim version (nvim -v)

NVIM v0.8.3

### Operating system/version

MacOS

### Output of :AerialInfo

not an editor command

### Describe the bug

What is the equivalent of require('aerial').setup({}) in you have a init.vim (no Lua) config

### Steps To Reproduce

What is the equivalent of require('aerial').setup({}) in you have a init.vim (no Lua) config

### Expected Behavior

What is the equivalent of require('aerial').setup({}) in you have a init.vim (no Lua) config

**Comment by stevearc** [comment]
You can use a `:help lua-heredoc`

example:
```vim
lua << EOF
require("aerial").setup({})
EOF
```
