### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by girishji** [stevearc/aerial.nvim#233]
### Neovim version (nvim -v)

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@HMBRW-A-001-M1-004.local

### Operating system/version

macos 12.6.3

### Output of :AerialInfo

Aerial Info
-----------
Filetype: lua
Configured backends:
  treesitter (supported) (attached)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct

### Describe the bug

Error executing vim.schedule lua callback: ...im/0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:499: bad argument #2 to 'handler' (string expected, got nil)
stack traceback:
	[C]: in function 'handler'
	...im/0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:499: in function 'match_preds'
	...im/0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:640: in function 'matches'
	.../nvim/lazy/nvim-treesitter/lua/nvim-treesitter/query.lua:254: in function '(for generator)'
	...lazy/aerial.nvim/lua/aerial/backends/treesitter/init.lua:65: in function 'fetch_symbols'
	...share/nvim/lazy/aerial.nvim/lua/aerial/backends/util.lua:10: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

### Steps To Reproduce

It happens occasionally

### Expected Behavior

na

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/aerial.nvim",
    config = function()
      require("aerial").setup({
        -- add your aerial config here
      })
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "c", "lua" },
        auto_install = true,
        highlight = { enable = true },
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

In aerial/backends/util.lua, maybe check for 'bufnr ~= nil' in line 10

**Comment by stevearc** [comment]
Sorry, this does not repro for me. The issue is not that the bufnr is nil, but rather it looks like the pattern being passed to a predicate is nil. Not quite sure how this could happen, but if it does it should be deterministic. Can you provide a sample file that triggers this error, and any more specific repro steps?
