### ISSUE TITLE
[Feature request] Close on select only if aerial is opened in floating window

### ISSUE THREAD

**Issue by Bekaboo** [stevearc/aerial.nvim#234]
Is it possible to configure aerial in a way such that it will automatically close after `<CR>` if it is opened in a floating window but will not automatically close if it is opened as a side bar? Thanks in advance!

**Comment by JoseConseco** [comment]
YOu can check if window is floating with
if vim.api.nvim_win_get_config(winid).zindex then ...
then plug it into:
`["<CR>"] = { callback = function() aerial.select(); aerial.close() end, desc = "", nowait = true },`

**Comment by Bekaboo** [comment]
Thanks it works, for future readers:

```lua
local aerial = require('aerial')

aerial.setup({
  keymaps = {
    ['<CR>'] = {
      callback = function()
        local is_floating = vim.api.nvim_win_get_config(0).zindex ~= nil
        aerial.select()
        if is_floating then
          aerial.close()
        end
      end,
    },
    ...
})
