### ISSUE TITLE
bug: No LSP client found that supports symbols

### ISSUE THREAD

**Issue by adoyle-h** [stevearc/aerial.nvim#236]
### Neovim version (nvim -v)

v0.8.3

### Operating system/version

MacOS 12.2

### Output of :AerialInfo

Aerial Info
-----------
Filetype: go
Configured backends:
  lsp (supported) (attached)
  treesitter (supported)
  markdown (not supported) [Filetype is not markdown]
Show symbols: Array, Boolean, Class, Constant, Constructor, Enum, EnumMember, Event, Field, File, Function, Interface, Key, Method, Mod
ule, Namespace, Null, Number, Object, Operator, Property, String, Struct, TypeParameter, Variable

### Describe the bug

It sometimes show the warning "No LSP client found that supports symbols" when I opened a ".go" file.
But the LSP of golang is attached, and the aerial is working well in the same buffer.

`:LspInfo`

<img width="741" alt="CleanShot 2023-03-29 at 21 13 17@2x" src="https://user-images.githubusercontent.com/1998490/228549037-28eed291-c94e-4e11-bfb1-7e004f9bc486.png">

### Steps To Reproduce

I don't know.

### Expected Behavior

Do not notify this warning.

**Comment by stevearc** [comment]
Hard to tell exactly what's happening from this description, but I found where some of the LSP logic could potentially disagree and cause a conflict. Can you try with this patch and see if it fixes it? If not, can you provide some more information? Things like
- What are all of the LSP clients that are attached to the buffer?
- When does the message appear? (when the file is opened? When you open aerial? Randomly while editing the file?)

**Comment by tomtomjhj** [comment]
I'm still experiencing similar problem when using lsp backend with texlab (`backends = { tex = {'lsp'}, }`).

some observations:
* Aerial works well most of the time, but after editing for some time, it starts to produce this error.
* I get "No LSP client found that supports symbols" message whenever I type something in insert mode.
* Interestingly, the `AerialOpen` panel works properly: if I add a `\section{title}`, the new section is displayed in the panel, but it still prints the error message.

**Comment by stevearc** [comment]
The fact that it seems to still be working is the confusing part. That means that the active buffer continues to have a functioning LSP client with a symbols provider attached to it. The only thing I can think of is maybe something has caused aerial to try to attach to a different buffer somehow, and that buffer doesn't have a client. I've added the buffer number to the error message. If you see it again, can you confirm if the buffer number is the number of the current file?

**Comment by adoyle-h** [comment]
@stevearc Sorry for the late response. The latest commit looks good to me.

**Comment by milanglacier** [comment]
I have the same issue, but the problem only happens when use `:q!` to quit a buffer (I can reproduce the problem with `R` and `go`, but not with `python`, interesting).


It is worth to note that when you use `:q!` to quit a buffer, the buffer will be detached from the lsp (say a go buffer will detach from `gopls` after `:q!`)

I think this might related to how we handle the detach event:

https://github.com/stevearc/aerial.nvim/blob/07039ea63b562caf9017a223d14eebfa1fc085c1/lua/aerial/backends/lsp/init.lua#L149

**Comment by milanglacier** [comment]
I find a way to *"bypass"* this bug:

I find that if I commented out the `on_attach` specification in my config, then such warning when using `:q!` to quit a buffer will not happen:

change the config from this:

```lua
    require('aerial').setup {
        backends = { 'lsp', 'treesitter', 'markdown' },
        close_automatic_events = { 'unsupported' },
        default_bindings = true,
        filter_kind = false,
        show_guides = true,
        on_attach = function(bufnr)
            bufmap(bufnr, 'n', '<leader>lo', '<cmd>AerialToggle!<CR>', {
                desc = 'lsp symbol outline',
            })
        end,
    }

```

to this

```lua
    require('aerial').setup {
        backends = { 'lsp', 'treesitter', 'markdown' },
        close_automatic_events = { 'unsupported' },
        default_bindings = true,
        filter_kind = false,
        show_guides = true,
        -- on_attach = function(bufnr)
        --     bufmap(bufnr, 'n', '<leader>lo', '<cmd>AerialToggle!<CR>', {
        --         desc = 'lsp symbol outline',
        --     })
        -- end,
    }

```

then the warnings will not be yielded.

However, the thing is I cannot produce the exactly same issue using a minimal init lua template (as per the github issue template). So I will leave my personal "workaround" here and to see if I can find a reproducible minimal init file.

**Comment by stevearc** [comment]
I believe this is the same as #249, and is also fixed
