### ISSUE TITLE
bug: Closing Aerial in vertical split focuses the other window

### ISSUE THREAD

**Issue by im-n1** [stevearc/aerial.nvim#241]
### Neovim version (nvim -v)

0.8

### Operating system/version

Linux

### Output of :AerialInfo

Aerial Info
-----------
Filetype: python
Configured backends:
  treesitter (supported) (attached)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct

### Describe the bug

After closing Aerial on in window with vertical split the other window get focused.

### Steps To Reproduce

1. 2 windows in vertical split like A|B
2. B in in focus
3. open aerial on the left side
4. close aerial
5. window A is focused

### Expected Behavior

window B is focused

### Additional context

my plugin setup:

```lua
	use({
		"stevearc/aerial.nvim",
		config = function()
			require("aerial").setup({
				-- Priority list of preferred backends for aerial.
				-- This can be a filetype map (see :help aerial-filetype-map)
				backends = { "treesitter", "lsp", "markdown", "man" },
				layout = {
					width = 50,
					default_direction = "left",
					placement = "window",
					-- preserve_equality = false,
				},
				-- A list of all symbols to display. Set to false to display all symbols.
				-- This can be a filetype map (see :help aerial-filetype-map)
				-- To see all available values, see :help SymbolKind
				close_automatic_events = { "unfocus", "switch_buffer" },
				filter_kind = {
					"Class",
					"Constructor",
					"Enum",
					"Function",
					"Interface",
					"Module",
					"Method",
					"Struct",
				},
				nerd_font = true,
				-- When you fold code with za, zo, or zc, update the aerial tree as well.
				-- Only works when manage_folds = true
				link_folds_to_tree = false,

				-- Options for opening aerial in a floating win
				float = {
					-- Controls border appearance. Passed to nvim_open_win
					border = "rounded",
				},
			})
		end,
	})

```

**Comment by stevearc** [comment]
Should be fixed!

**Comment by im-n1** [comment]
Yes! Incredible speed, thanks a milion.
