### ISSUE TITLE
Keeping focus on aerial window after jumping to symbol

### ISSUE THREAD

**Issue by matko031** [stevearc/aerial.nvim#243]
I just installed Aerial and I have to say I love it! I was going through the docs and I was looking for an option to keep the focus on aerial window after jumping to a symbol, but I couldn't find it. Does that option exist?

**Comment by stevearc** [comment]
Yep, there's an action called `scroll` (could probably be named better) and it's bound to `p` by default. You can do `g?` from inside the aerial window and it will show you all the keybindings as well as a short description of what they all do.
