### ISSUE TITLE
Can't get it work in vue files. 

### ISSUE THREAD

**Issue by rolf-stargate** [stevearc/aerial.nvim#245]
**Language**: vue
**AerialInfo**: Aerial Info                                                                                      
-----------
Filetype: vue
Configured backends:
  treesitter (not supported) [No query file for 'vue']
  lsp (not supported) [No LSP client found that supports symbols]
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct

The minimal amount of code that demonstrates the missing symbol:
```
<template lang='pug'>
.foo
  .bar
    .baz
      .qux
        .quux
          .quuz
</template>

<script>
export default {
 setup () {
   function foo () {
     return {}
   }
   return {}
 }
}
</script>


<style lang='scss' scoped>
.foo {
  .bar {
    .baz {
      .qux {
        .quux {
          .quuz {
            color: red;
          }
        }
      }
    }
  }
}
</style>
```

**Expected symbol**: Any symbol

**LspInfo***: 
Detected filetype:   vue
 
 2 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, bufnr: [1])
 	filetypes:       typescriptreact, html, typescript, css, scss, jsonc, less, graphql, markdown.mdx, javascript, vue, handlebars, yaml, json, markdown, javascriptreact, python, lua, luau
 	autostart:       false
 	root directory:  /home/rolf
 	cmd:             <function>
 
 Client: copilot (id: 2, bufnr: [1])
 	filetypes:       
 	autostart:       false
 	root directory:  Running in single file mode.
 	cmd:             node /home/rolf/.local/share/nvim/site/pack/packer/start/copilot.vim/copilot/dist/agent.js
 
 Configured servers list: rust_analyzer, lua_ls, pyright, jsonls

Can't get it to detect symbols but I'm not sure if I missed something. As far as I can tell LSP and Treesitter are working fine.

**Comment by stevearc** [comment]
There's no LSP server running that supports document symbols, and no one has added treesitter support for vue yet (the list of supported languages is here: https://github.com/stevearc/aerial.nvim/tree/master/queries)

I suspect this is going to be even trickier than usual, because it looks like vue files rely heavily on language injections, and aerial doesn't yet support getting symbols from injected languages. That's a larger task and I can't provide any ETA on it (PR's always welcome).

**Comment by rolf-stargate** [comment]
Ok I understand. Still an amazing plugin and thanks for your time.

**Comment by rolf-stargate** [comment]
I got it working. It was an oversight on my part. I had the language server volar(vue-language-server) installed but it wasn't attached to the buffer. Now it is working fine.
