### ISSUE TITLE
Allow full control of window position by opening in current window

### ISSUE THREAD

**Issue by mrjones2014** [stevearc/aerial.nvim#248]
It would be great if aerial had an option to just open in the current window. This would give users full control over placement and allow more complicated setups. 

For context, I’m asking in relation to this: https://github.com/nvim-tree/nvim-tree.lua/discussions/2173

**Comment by stevearc** [comment]
I've added a new function `aerial.open_in_win` that should do what you want. LMK if you encounter any issues

**Comment by mrjones2014** [comment]
Works great, thank you!
