### ISSUE TITLE
the function return pointer in cpp

### ISSUE THREAD

**Issue by GPN211314** [stevearc/aerial.nvim#25]
**Language**: cpp
**AerialInfo**: 
-----------
Filetype: cpp
Configured backends:
  lsp (not supported)
  treesitter (supported) (attached)
  markdown (not supported)
Show symbols: Class, Constructor, Enum, Function, Interface, Method, Struct

The minimal amount of code that demonstrates the missing symbol:
```
int* bar() {}
```

**Expected symbol**: bar

**Comment by stevearc** [comment]
Thanks for the report!
