### ISSUE TITLE
Show symbols defined in other files

### ISSUE THREAD

**Issue by augustocdias** [stevearc/aerial.nvim#255]
Aerial currently shows the outline of the symbols in the current buffer. Some languages allow to spread the definition of symbols across different files. Take rust for example. I can add functions to structs anywhere in the project. It would be nice if the outline could show those symbols as well. I know that with treesitter this is not feasible but maybe it is possible with lsp.

**Comment by stevearc** [comment]
This idea has been suggested before (for golang) in #81. It's a good idea, and it sounds useful, but it's unfortunately outside the scope of aerial. It requires too much custom logic and it wouldn't work well with some existing features.
