### ISSUE TITLE
bug:  when there are no symbols navigation window gives error

### ISSUE THREAD

**Issue by petobens** [stevearc/aerial.nvim#256]
### Neovim version (nvim -v)

Latest Master

### Operating system/version

Arch Linux

### Output of :AerialInfo

-

### Describe the bug

If I run `:AerialNavToggle` on a buffer that doesn't have symbols I get:
```
Error executing Lua callback: ...ocal/share/nvim/lazy/aerial.nvim/lua/aerial/nav_view.lua:227: attempt to index local 'symbol' (a nil value)
stack traceback:
        ...ocal/share/nvim/lazy/aerial.nvim/lua/aerial/nav_view.lua:227: in function 'focus_symbol'
        ...ocal/share/nvim/lazy/aerial.nvim/lua/aerial/nav_view.lua:338: in function 'open'
        ...ocal/share/nvim/lazy/aerial.nvim/lua/aerial/nav_view.lua:346: in function 'toggle'
        ...local/share/nvim/lazy/aerial.nvim/lua/aerial/command.lua:124: in function <...local/share/nvim/lazy/aerial.nvim/lua/aerial/command.lua:123>
```

On the other hand `:AerialToggle` opens without an error (and simply reports that there are no symbols).

### Steps To Reproduce

See above

### Expected Behavior

Exit/ continue gracefully

### Minimal example file

-

### Minimal init.lua

```Lua
-
```

**Comment by stevearc** [comment]
Fixed. Thanks for the report!

**Comment by petobens** [comment]
Thank you!
