### ISSUE TITLE
bug: Nvim 0.9.0: vim.treesitter.query.get_node_text() is deprecated

### ISSUE THREAD

**Issue by angelidis** [stevearc/aerial.nvim#258]
### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

Windows 11

### Output of :AerialInfo

Aerial Info
-----------
Filetype: lua
Configured backends:
  treesitter (supported) (attached)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct

### Describe the bug

i get the following warning:

`
vim.treesitter.query.get_node_text() is deprecated, use vim.treesitter.get_node_text() instead. :help deprecated
This feature will be removed in Nvim version 0.10
stack traceback:
	...im-win64\share\nvim\runtime/lua/vim/treesitter/query.lua:274: in function 'get_node_text'
	...gged\aerial.nvim/lua/aerial/backends/treesitter/init.lua:83: in function 'fetch_symbols'
	...gs\nvim\plugged\aerial.nvim/lua/aerial/backends/init.lua:126: in function 'attach'
	...gs\nvim\plugged\aerial.nvim/lua/aerial/backends/init.lua:142: in function 'get'
	...gs\nvim\plugged\aerial.nvim/lua/aerial/backends/init.lua:220: in function 'attach'
	...ngs\nvim\plugged\aerial.nvim/lua/aerial/autocommands.lua:85: in function 'cb'
	vim/_editor.lua:263: in function <vim/_editor.lua:262>
`

### Steps To Reproduce

just nvim with aerial and treesitter configured

### Expected Behavior

expected to not receive this warning

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/aerial.nvim",
    config = function()
      require("aerial").setup({
        -- add your aerial config here
      })
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "c", "lua" },
        auto_install = true,
        highlight = { enable = true },
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
I put in a fix for this in March a6b86fd357f184ad9f146245f8d34c9df0

Are you still seeing this error on the latest version?

**Comment by angelidis** [comment]
hi Steven!

It works great now.
Thanks for maintaining such a great plugin!

**Comment by angelidis** [comment]
this was resolved way back in may. sorry for not closing it earlier.
