### ISSUE TITLE
bug: Namespace.function() is not shown in outline

### ISSUE THREAD

**Issue by filchristou** [stevearc/aerial.nvim#260]
### Neovim version (nvim -v)

0.9.1

### Operating system/version

debian 11

### Output of :AerialInfo

Aerial Info                                                                                        
-----------
Filetype: julia
Configured backends:
  treesitter (supported) (attached)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: all symbols

### Describe the bug

When functions are written in the form of Whatever.myfunction, it doesn't seem to be shown in the outline
Example:
![image](https://github.com/stevearc/aerial.nvim/assets/27723218/533329c1-8f95-4a5a-8881-58bc5d7eb2ef)

However SymbolsOutline have no problem with that (meaning it's not an LSP/tree-sitter thing):
![image](https://github.com/stevearc/aerial.nvim/assets/27723218/53a0a727-0688-404b-9b81-74ceb318cfea)

### Steps To Reproduce

1.
Write a *.jl file with the following code
```
module Alpha
    struct A end
    myfunca(x::A) = isnothing(x) ? x : 10 

    module Beta
	import ..Alpha
	struct B end
	Alpha.myfunca(x::B) = isnothing(x) ? x : 20
    end
end
```
2. Execute `:AerialToggle`

### Expected Behavior

`myfunca` should be shown two times

### Minimal init.lua

```Lua
1. Cloned https://github.com/nvim-lua/kickstart.nvim
    2. Add julials LSP with :Mason
    3. install LanugageServer.jl in the general julia environment
Add the following to init.lua 

  {
    'stevearc/aerial.nvim',
    opts = {
      filter_kind=false,
    },
    -- Optional dependencies
    dependencies = {
      "nvim-treesitter/nvim-treesitter",
      "nvim-tree/nvim-web-devicons"
    },
  },
```
```


### Additional context

_No response_

**Comment by stevearc** [comment]
This was because you're using the treesitter backend and it didn't have support for namespaced short function definitions. The function should show up now

**Comment by filchristou** [comment]
Thanks for the fast reaction. It's not only namespaced short functions, but also namespaced normal ones.
The first is now fixed, but the second is still problematic.
E.g. in the following code, `aerial` will not parse `Alpha.myfuncb`
```
module Alpha
    struct A end
    myfunca(x::A) = isnothing(x) ? x : 10 
    function myfuncb(x::A)
	return ismissing(x) ? x : 10 
    end

    module Beta
	import ..Alpha
	struct B end
	Alpha.myfunca(x::B) = isnothing(x) ? x : 20
	function Alpha.myfuncb(x::B)
	    return ismissing(x) ? x : 20 
	end
    end
end
```
![image](https://github.com/stevearc/aerial.nvim/assets/27723218/9fbb1d11-4ce6-4041-9460-6859b978a79b)



Irrelevant, but is there a way to show the namespace of the function on the `aerial` outline ?

**Comment by stevearc** [comment]
Added support for non-short functions as well.

As for showing the namespace of the functions, I know approximately nothing about Julia, so I have no idea if that makes sense as a default behavior. If it does, I can change it pretty easily. Unfortunately there's no good way at the moment to customize it in your own config.

**Comment by filchristou** [comment]
Thanks a lot. Works as expected now.

> so I have no idea if that makes sense as a default behavior.

Generally, whenever the function defined belongs to a different module , it's a good idea to show the namespace.
Otherwise it would be very noisy to always show the function namespace, even if they belong to the native module (which generally it would be the majority)

Having a simple **heuristic** like if the method is defined as `Namespace.method()` then show it as `Namespace.method` in the outline would cover ca. 90% of the use cases, so it would be a reasonable and intuitive improvement.
However there are corner cases, e.g. if the user does `import Namespace: methodname` then the function `Namespace.methodname` can be "overloaded" without prepending the namespace.

**Comment by stevearc** [comment]
Makes sense! I've updated the logic to apply that heuristic. If declared with a namespace, the function should appear in aerial with that namespace.

**Comment by filchristou** [comment]
works as intended. thanks for the amazing support ! :tada:
