### ISSUE TITLE
Feature Request: store locations in jumplist

### ISSUE THREAD

**Issue by wbthomason** [stevearc/aerial.nvim#266]
Thanks for the excellent plugin! I would like to suggest a small tweak to better integrate with Neovim's existing navigation tools - saving the current location to the jumplist before jumping to a new symbol.

This would allow users to move between symbols with a combination of `aerial` and the standard `<c-o>`/`<c-i>`/etc. jump operators.

I think this should only take a 1-line (or so) change around here (although I haven't read through the codebase in depth): https://github.com/stevearc/aerial.nvim/blob/aff1bb8fecff83d3e3a2d544c4d4e6d65718bd19/lua/aerial/navigation.lua#L237-L241

Specifically, it should suffice to set the `'` register with `m'` just before jumping, if the user has jumping configured. If you're open to this, I'd be happy to make a PR.

**Comment by stevearc** [comment]
This seems like a good idea, sure!

**Comment by quolpr** [comment]
That will be a great feature, I really miss it

**Comment by wbthomason** [comment]
Finally got around to this in #305, sorry for the delay.

**Comment by stevearc** [comment]
Closed by #424
