### ISSUE TITLE
Map config values are discarded and reset to default

### ISSUE THREAD

**Issue by snezhniylis** [stevearc/aerial.nvim#27]
**Describe the bug**

This regression was introduced in recent [options lookup refactoring](https://github.com/stevearc/aerial.nvim/commit/1f1200b4f78af76a98a1e8b23f867bf445ab275d) (I presume).

The reason: https://github.com/stevearc/aerial.nvim/blob/master/lua/aerial/config.lua#L207 asserts that all the table options should be of list type, recreating them otherwise.

**To Reproduce**

1. Make sure `lspkind` is disabled.
2. ```lua
   vim.g.aerial = {
     icons = {
       Class = '*';
       Function = '*';
     }
   }
   ```
Default icons will be displayed.

**Comment by stevearc** [comment]
Apologies! I added test coverage for most of the config surface, but neglected the icons. Will get that fixed up.

**Comment by snezhniylis** [comment]
Thank you!
