### ISSUE TITLE
feature request/tuning: cursor positioning when jumping

### ISSUE THREAD

**Issue by emmanueltouzery** [stevearc/aerial.nvim#279]
when navigating using aerial, to jump to a symbol, aerial jumps at the beginning of the declaration of the symbol, not on the symbol itself. For instance, for `class Symbol`, the cursor will be at the beginning of `class`. For `export function symbol()`, the cursor will be at the start of the `function` keyword.

I'd prefer for the cursor to be at the start of the symbol... so `class |Symbol` and `export function |symbol()` -- to be clear, the cursor would be on top of the first letter of the symbol, not before it. The reason is that this enables further navigation using LSP. For instance, let's say I have a build error in a function, I use aerial to jump to the function declaration, now i'd like to use LSP to find the callers of the function. But my cursor is on the `function` keyword, not on the function name itself, and therefore the LSP "find references" doesn't work until I jump to the beginning of the next word, which is the function name.

It's totally a detail and a "comfort" issue.. but if possible, it would be a nice bonus. Otherwise aerial really is great, thank you for your work!

**Comment by stevearc** [comment]
I'm assuming that you're using the treesitter backend, because the LSP backend should already be doing basically this. I've added experimental support for this behavior in treesitter. You can enable it with this config option:

```lua
require("aerial").setup({
  treesitter = {
    experimental_selection_range = true,
  }
})
```

**Comment by emmanueltouzery** [comment]
thank you! you're correct, i'm using the treesitter backend.

It seems to me that it's working if I'm using the aerial sidebar, however it's not working when using the telescope interface. With the telescope interface, even with the experimental option, the cursor is still get positioned at the start of the line :(

Thank you!

**Comment by stevearc** [comment]
Ah, easy fix. Try again!

**Comment by emmanueltouzery** [comment]
thank you! this seems to work now. I guess i'll close the issue, and reopen if i find a glitch. Since you named the option 'experimental', if you prefer to keep it open, reopen it of course...
