### ISSUE TITLE
Specifying backends interactively

### ISSUE THREAD

**Issue by hongxuchen** [stevearc/aerial.nvim#280]
This is not a feature request for a particular treesitter language but a general one.

For me, I prefer LSP rather than treesitter. So LSP comes before treesitter in my backends priority settings. However I notice that sometimes, LSP gives worse results than treesitter (e.g., when I opened a C/C++ file with an incomplete build info file, clangd may miss quite a few symbols). But it seems that I have no choice to specify a backend with existing Aerial commands. I would very much like Aerial to have such a feature. I think this feature would also help users to easily setup a filetype map of backends without restarting nvim.

For the explicit specification behavior in the present of backend priorities, I prefer Aerial to always observes the priorities unless specified by the user in the current "LSP workspace" (per buffer specification is also acceptable to me).

**Comment by stevearc** [comment]
I've added the ability to override any option that accepts a filetype map by using a buffer-local variable. For example, you could set `vim.b.aerial_backends = { "lsp" }` to only use the LSP for the current buffer.

After you make this change, you'll probably want to refresh the symbols. You can do that with the newly-added function:
```lua
require("aerial").refetch_symbols()
```
