### ISSUE TITLE
feat: filtering based on child/parent node

### ISSUE THREAD

**Issue by WieeRd** [stevearc/aerial.nvim#285]
By default, aerial only displays more "significant" symbols, such as class and function.  
```python
a = 1

class Foo:
    def bar(self):
        pass
```
```
{C} Foo
└─{F} bar
```
This is a reasonable choice, as all the variables cluttering the aerial buffer is not desirable.

But in Lua, and some other languages, you have to use tables to mimic classes.
```lua
local a = 1

local Foo = {
  bar = function()
    -- stuffs
  end
}

local function baz()
  -- b a z
end
```
```
{F} bar
{F} baz
```
`Foo` gets filtered out because it's just a variable.
And now `bar` is displayed as if it's a top level function like `baz`.
This feels... a bit weird to me.

Obviously, I could include variables in the filter.
But that will also make it include all the trivial variables like `a` as well.

If filters could optionally put child/parent nodes of current symbol into consideration,  
we can get `Foo` to be displayed because it has significant node `bar` as a child,
while filtering out `a` because it's all by itself.

This sounds quite awkward to implement and I'm probably asking for too much lol.
But I still think it's a cool concept and is worth taking a look someday.

**Comment by stevearc** [comment]
This is something that is language-specific, and also depends a lot on how you use the language. For example, if you define your class as
```lua
local Foo = {}

function Foo.bar()
  --
end
```
Then it will show up as `Foo.bar` in aerial, which is presumably less confusing. The trouble is, lua is so flexible that the desired behavior is going to be different depending on what conventions you're using.

That makes it difficult to add good logic for this in aerial itself, but you can already add support for this yourself using the treesitter backend. #220 added some pretty generic extension points that you could use to inject custom logic to decide which symbols to include and how to display them.

**Comment by WieeRd** [comment]
Wasn't aware of post process API, I'll be messing around with it. Thanks.
