### ISSUE TITLE
`:Telescope aerial` showing way less results than `:Telescope lsp_document_symbols` picker

### ISSUE THREAD

**Issue by macintacos** [stevearc/aerial.nvim#29]
**Describe the bug**

Hello! In the README, it says:

> If you have telescope installed, there is an extension for fuzzy finding and jumping to symbols. It functions similarly to the builtin `lsp_document_symbols` picker.

For me, it seems like Aerial is showing way less results than `lsp_document_symbols`. Here's the Telescope builtin results for a sample file I have (excuse the whacky colors):

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/8128941/144342834-cb1595f6-5e34-42d2-aaad-8afd6078d377.png">

And then this is what I see with `:Telescope aerial` on the same file (fwiw, this is also what's shown in the Aerial window, so I don't think this is a Telescope problem)

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/8128941/144343004-40cd262f-2f14-4e3e-8065-b6550aea101e.png">

Am I doing something wrong? My basic configuration looks like this (I install LSP backends with nvim-lsp-installer, and things seem to be configured okay for most things):

```lua
local lsp_installer = require("nvim-lsp-installer")
lsp_installer.on_server_ready(function(server)
    local opts = {}
    local aerial = require("aerial")

    opts.on_attach = function(client)
        -- other configs

        aerial.on_attach(client)
    end

    server:setup(opts)
end)
```

**System information**
- OS: macOS 12.0.1
- Neovim version: 0.6.0
- AerialInfo:

```
Aerial Info
-----------
Filetype: lua
Configured backends:
  lsp (supported) (attached)
  treesitter (supported)
  markdown (not supported)
Show symbols: Class, Constructor, Enum, Function, Interface, Method, Struct
```

**To Reproduce**
1. Compare the output of `:Telescope aerial` and `:Telescope lsp_document_symbols`

**Comment by stevearc** [comment]
This is by design, though the documentation could be more clear. Aerial doesn't show all document symbols by default because it's very noisy. There are a lot of symbols (e.g. Array, Boolean, Null) that don't really help you get a summary of your file. See `:help aerial_filter_kind` for detailed information.

If you do want to see all the symbols that LSP provides, you can disable filtering by setting the `filter_kind` option to `false`. If you do that, it should behave exactly the same as `:Telescope lsp_document_symbols`

**Comment by macintacos** [comment]
Ah, thanks for that! FWIW, I _do_ want to see all that noise, especially in Telescope where really what I'm trying to do is jump to a symbol I know is in the document. Perhaps that should be the default for the telescope picker?

**Comment by stevearc** [comment]
I think the aerial picker should only show the symbols that are in the aerial window. If you want that behavior, why not just use `:Telescope lsp_document_symbols`?

**Comment by macintacos** [comment]
Touché 🙂
