### ISSUE TITLE
All folds expand automatically when using diffview.nvim

### ISSUE THREAD

**Issue by thenbe** [stevearc/aerial.nvim#299]
### Neovim version (nvim -v)

NVIM v0.9.2 Build type: Release LuaJIT 2.1.1693350652

### Operating system/version

 - system: `"x86_64-linux"`  - host os: `Linux 6.1.55, NixOS, 23.11 (Tapir), 23.11.20231001.fdd898f`

### Output of :AerialInfo

```
Aerial Info
-----------
Filetype: lua
Configured backends:
  treesitter (supported) (attached)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: all symbols
```

### Describe the bug

https://github.com/stevearc/aerial.nvim/assets/33713262/3174f8ea-ea53-4f08-b27f-03a0c777dba4

### Steps To Reproduce

1. CD into the `aerial.nvim` directory
1. Open nvim, run `DiffviewOpen d7577c`.
1. Move your cursor into the window on the right. i.e. from the File Panel into the first diff window.
1. (bug) Observe that all folds have been automatically expanded.
1. Move your cursor into the window on the far right. i.e. from the first diff window into the second diff window.
1. (bug) Observe that all folds have been automatically expanded.
1. Press `tab` to view the next file's diff. Press `tab` again. This should take you to the next file/commit diff view and back.
1. Observe that all folds have been "fixed" to their original state. Moving your cursor between windows will not expand them automatically anymore.

### Expected Behavior

Folds should not be automatically expanded upon moving cursor to diff window.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/aerial.nvim",
    config = function()
      require("aerial").setup({
				manage_folds = true,
				filter_kind = false,
				open_automatic = function()
					-- noop
				end,
      })
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "c", "lua" },
        auto_install = true,
        highlight = { enable = true },
      })
    end,
  },
  -- add any other plugins here
	{
		"sindrets/diffview.nvim",
		lazy = false,
		dependencies = { "nvim-lua/plenary.nvim", "lewis6991/gitsigns.nvim" },
		config = true,
	},
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

- This bug doesn't happen for all files and all commits. My guess is that there needs to be a certain symbol in the file or diff for the behavior to trigger. Setting `filer_kind` to false will cause this to be fixed on some diffs, while fixing(?!) it on other diffs that were previously affected.
- This is not affected by what `open_automatic` returns. Merely declaring the `open_automatic` key will cause this bug to occur.

**Comment by stevearc** [comment]
Thanks for the detailed repro! This was a tricky one, but being able to replicate it on my own machine helped enormously.
