### ISSUE TITLE
[Feature Request] Equal window size after open

### ISSUE THREAD

**Issue by ten3roberts** [stevearc/aerial.nvim#3]
When the aerial window opens, it will 'steal' size from the parent window from which it was opened from. If you have many vertical splits open the split with an Aerial window open will be slightly thinner.

I suggest an option that will automatically execute `wincmd =` on window opening, which will balance the size of all windows except fixwidth windows like aerial.

Another option would be to respect the value of `equalalways`

**Comment by stevearc** [comment]
Sounds good to me! I'll make this the default behavior. If this is a problem for anyone reading this issue, file another issue and I can add an option to disable.
