### ISSUE TITLE
bug: Move commands with lazy loading

### ISSUE THREAD

**Issue by luckasRanarison** [stevearc/aerial.nvim#301]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-1301+g30d311ebc

### Operating system/version

Fedora 37

### Output of :AerialInfo

Aerial Info                                                                                                                                         
-----------                                                                                                                                         
Filetype: c                                                                                                                                         
Configured backends:                                                                                                                                
  treesitter (supported) (attached)                                                                                                                 
  lsp (not supported) [No LSP client found that supports symbols]                                                                                   
  markdown (not supported) [Filetype is not markdown]                                                                                               
  man (not supported) [Filetype is not man]                                                                                                         
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct       

### Describe the bug

Move commands like `AerialNext` and `AerialPrev` don't work the first time the plugin is called, though it works when setting `lazy_load` in the options to `false`. Is that an intended behaviour? And I if I use it with lazy_load set to false and use some lazy loading options with lazy.nvim like `cmd = { "AerialNext" }` it also doesn't work on the first call, I don't know if I should blame lazy.nvim for that.

### Steps To Reproduce

nvim -u init.lua test.c
use `:AerialNext<CR>`

### Expected Behavior

`AerialNext`, `AerialPrev` and `AerialGo` should directly work when calling the plugin for the first time.

### Minimal example file

#include <stdio.h>

void hello() {
    printf("hi");
}

int main() {
    hello();
    return 0;
}

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/aerial.nvim",
    config = function()
      require("aerial").setup({
        -- add your aerial config here
      })
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "c", "lua" },
        auto_install = true,
        highlight = { enable = true },
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
This is a known bug. The issue is that fetching the symbols of a file is not instantaneous. When you `AerialNext`, it loads aerial and begins to attach to the buffer. When the attach finishes and we get the symbols for the buffer, the `AerialNext` has already resolved (as a no-op). Subsequent calls will work as expected. This command drop will happen any time the command triggers the loading + setup of aerial.

I have some ideas to fix it; I just haven't gotten to them yet. I could either add a `vim.wait` to block the motion command until aerial attaches, or I could store a short history of commands and replay the recent ones when aerial first attaches to a buffer.

**Comment by stevearc** [comment]
fixed

**Comment by luckasRanarison** [comment]
Thanks!
