### ISSUE TITLE
Different filter for navigation and display

### ISSUE THREAD

**Issue by Nekketsu** [stevearc/aerial.nvim#306]
Would it be possible to set a different filter for the navigation commands `AerialNext`, `AerialPrev` and for display options?
I would like to show all symbols, so I set `filter_kind = false`, but I'd like to navigate with `AerialNext` and `AerialPrev` using some filters like:
```
 filter_kind = {
    "Class",
    "Constructor",
    "Enum",
    "Function",
    "Interface",
    "Module",
    "Method",
    "Struct",
  },
```

**Comment by stevearc** [comment]
This would be very complicated and is out of scope. If you want a more (or less) granular way to navigate around by symbol, I would recommend using [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects)
