### ISSUE TITLE
feat: open aerial.nvim in the current buffer

### ISSUE THREAD

**Issue by niqodea** [stevearc/aerial.nvim#308]
Hello aerial.nvim team,

I'm a fan of your plugin and had a suggestion. Inspired by the netrw style of file exploration and Drew Neil's ["Oil and Vinegar" article](http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer), I thought it might be useful to allow aerial to open in the current buffer.

## Proposal:
Add an option to access the aerial view directly in the current buffer, alongside the existing side buffer and popup navigator methods. The aerial view would allow the user to jump back in the file it was generated from by pressing enter on the symbols.

Depending on the complexity it introduces, it could make sense to have this aerial view automatically update if the file it was generated from has been modified in another buffer. This, however, is definitely not a must-have. I think a simple refresh command could also work.

## Benefits:
- Reduce context switching.
- Familiar experience for netrw users.

Thanks for the great work!

**Comment by stevearc** [comment]
Is this not already addressed with `:AerialOpen float` and `:AerialNavOpen`?

**Comment by niqodea** [comment]
I tried using both of those to have an approximation of what I want but ultimately I am sticking with the classic `:AerialOpen` by the side for now. For example, both of those options do not populate the history stack, so you can't go back there with `ctrl-I`/`ctrl-O` (actually netrw also misbehaves in this case, but I digress). Here are some other reasons why:

- `:AerialOpen float`
  - The floating panel does not match the look and feel of netrw (moreover, it is thin and its height is cursor-dependent by default)
  - By default, it stays open after pressing enter to go back to the buffer, which is a bit awkward as it keeps covering the original buffer
  - When trying switching to adjacent buffers while focused on the floating panel, you still need to "escape" the original buffer first
- `:AerianNavOpen`
  - It appears in the central part of the screen and is not bound to a buffer visually
  - You cannot run it on a buffer without taking immediate action (e.g. you cannot open nav, switch to another buffer with nav as visual reference, go back to nav)
  - Symbols at different hierarchy levels are not presented in the same list (this is one thing I really like about the default `AerialOpen` compared to nav)

**Comment by stevearc** [comment]
For `:AerialOpen float`:
> The floating panel does not match the look and feel of netrw (moreover, by default it is thin and its height is cursor-dependent)

The layout of the floating window can be customized. See the `float` config table in the options

> By default, it stays open after pressing enter to go back to the buffer, which is a bit awkward as it keeps covering the original buffer

This behavior previously was fixable with a config option, but I recently made it the default to close the window upon exit

> When trying switching to adjacent buffers while focused on the floating panel, you still need to "escape" the original buffer first

This sounds like the one thing that isn't currently handled, and honestly I'm not going to add support for it. The need for "open symbols in current window, then switch to another window and do stuff" is very niche.

**Comment by niqodea** [comment]
Fair! I will use `:AerialOpen float` as you suggested, thanks. The fact that it now automatically closes when unfocused makes it much more usable.

For reference, if anyone is interested in getting an immersive and consistent experience with the float aerial window:

```lua
require('aerial').setup({
    layout = {
        max_width = 0.9,
        min_width = 0.9,
    },
    float = {
        relative = 'win',
        max_height = 0.9,
        min_height = 0.9,
    }
})

```
