### ISSUE TITLE
[Feature request] Add horizontal padding (spacing) to each item

### ISSUE THREAD

**Issue by xuanhung1509** [stevearc/aerial.nvim#313]
![image](https://github.com/stevearc/aerial.nvim/assets/89293664/173bdadd-f485-42e6-ad74-f0bf373d578c)

As the title describes, I'd appreciate a little padding. Currently, each item (if being top-most one) is sitting right next to the border, and the cursor is overlapping part of the item. A desired result would be like `Neo-tree` (screenshot below). 

![image](https://github.com/stevearc/aerial.nvim/assets/89293664/2e57d4d1-35c0-4be3-8867-8f339cd9ce7e)

**Comment by stevearc** [comment]
I think the spacing is fine. If you dislike the aesthetic of the cursor atop an icon you could write an autocmd to move your cursor to the symbol name, or hide the cursor, or you could change the cursor highlight
