### ISSUE TITLE
Can I write query files for a custom language myself?

### ISSUE THREAD

**Issue by paradoxskin** [stevearc/aerial.nvim#326]
I just completed the treesitter plug-in of pico8, and today I want to add the aerial feature to position the function. I briefly referred to the query files in other languages and found that it is not complicated, so I completed it quickly and it can run normally in the playground. But it cannot be displayed in aerial. 
![tmp](https://github.com/stevearc/aerial.nvim/assets/45301314/b1882a4b-e742-4f5c-bd1c-c44a3a3d5391)
![tmp](https://github.com/stevearc/aerial.nvim/assets/45301314/76661846-824b-4a30-9792-0196fea7ee05)
I don’t know if there are any other steps to complete, such as adding something to the source code of aerial.

**Comment by paradoxskin** [comment]
It just work when I change `symbol` to `type`

**Comment by paradoxskin** [comment]
Ops, I find the problem... The SHA-1 of my local `aerial.nvim` is `3a3baf` but I Referenced the `master`'s query file...

**Comment by stevearc** [comment]
Yes, you'll want to make sure that aerial is up-to-date. You'll also want to make sure that the query file is located at `after/queries/<language>/aerial.scm`
