### ISSUE TITLE
feature: change markdown header icons

### ISSUE THREAD

**Issue by petobens** [stevearc/aerial.nvim#327]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-1562+g5b45efbee6

### Operating system/version

Arch Linux

### Output of :AerialInfo

Aerial Info
-----------
Filetype: markdown
Configured backends:
  markdown (supported) (attached)
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct

### Describe the bug

I was wondering whether I could have in the aerial window the same header icons I use in my main markdown file. I tried adding:
```lua
    icons = {
        markdown = { Interface = '󰪥' },
    },
```
but have no clear idea whether i) I can add different icons for different hierarchies  and ii) change those icon colors. Thanks in advance!

![image](https://github.com/stevearc/aerial.nvim/assets/2583971/8902d2d5-7e8f-4522-8a5c-5e91454520cc)

### Steps To Reproduce

-

### Expected Behavior

-

**Comment by stevearc** [comment]
No, currently there's no way to set a different icon or color for the same type of symbol

**Comment by petobens** [comment]
Ok. Feel free to close if this is not planned. Thanks!

**Comment by mcauley-penney** [comment]
It seems like this is possible with the existing Treesitter Markdown parser. You just need to have a name for the icons. I have a branch for this

<img width="4314" height="5670" alt="Image" src="https://github.com/user-attachments/assets/cf8a2cfd-3aeb-4407-bc2b-06be9eee1670" />

**Comment by petobens** [comment]
@mcauley-penney thanks! Can you show you actually achieve what is shown in the image?

**Comment by mcauley-penney** [comment]
> Can you show you actually achieve what is shown in the image

Yeah, this is a screenshot of [my fork](https://github.com/mcauley-penney/aerial.nvim/tree/fix-md-header-icons). 

The relevant portion of the configuration is 

```
kind_icons = {
  Array = " 󰅪 ",
  BlockMappingPair = " 󰅩 ",
  Boolean = "  ",
  BreakStatement = " 󰙧 ",
  Call = " 󰃷 ",
  CaseStatement = " 󰨚 ",
  Class = "  ",
  Color = "  ",
  Constant = "  ",
  Constructor = " 󰆧 ",
  ContinueStatement = "  ",
  Copilot = "  ",
  Declaration = " 󰙠 ",
  Delete = " 󰩺 ",
  DoStatement = " 󰑖 ",
  Element = " 󰅩 ",
  Enum = "  ",
  EnumMember = "  ",
  Event = "  ",
  Field = "  ",
  File = "  ",
  Folder = "  ",
  ForStatement = "󰑖 ",
  Function = " 󰆧 ",
  GotoStatement = " 󰁔 ",
  Identifier = " 󰀫 ",
  IfStatement = " 󰇉 ",
  Interface = "  ",
  Keyword = "  ",
  List = " 󰅪 ",
  Log = " 󰦪 ",
  Lsp = "  ",
  Macro = " 󰁌 ",
  MarkdownH1 = " 󰉫 ",
  MarkdownH2 = " 󰉬 ",
  MarkdownH3 = " 󰉭 ",
  MarkdownH4 = " 󰉮 ",
  MarkdownH5 = " 󰉯 ",
  MarkdownH6 = " 󰉰 ",
  Method = " 󰆧 ",
  Module = " 󰅩 ",
  Namespace = " 󰅩 ",
  Null = " 󰢤 ",
  Number = " 󰎠 ",
  Object = " 󰅩 ",
  Operator = "  ",
  Package = " 󰆧 ",
  Pair = " 󰅪 ",
  Property = "  ",
  Reference = "  ",
  Regex = "  ",
  Repeat = " 󰑖 ",
  Return = " 󰌑 ",
  RuleSet = " 󰅩 ",
  Scope = " 󰅩 ",
  Section = " 󰅩 ",
  Snippet = "  ",
  Specifier = " 󰦪 ",
  Statement = " 󰅩 ",
  String = "  ",
  Struct = "  ",
  SwitchStatement = " 󰨙 ",
  Table = " 󰅩 ",
  Terminal = "  ",
  Text = " 󰀬 ",
  Type = "  ",
  TypeParameter = "  ",
  Unit = "  ",
  Value = "  ",
  Variable = "  ",
  WhileStatement = " 󰑖 ",
}, 

return {
  "mcauley-penney/aerial.nvim",
  branch = "fix-md-header-icons",
  opts = {
    icons = kind_icons
  }
} 
```

**Comment by Rom888** [comment]
Can we reopen this issue?

**Comment by alexmozaidze** [comment]
This should be re-opened and the feature added. This is much too useful.
