### ISSUE TITLE
bug: AerialLine should take precedence over other highlights

### ISSUE THREAD

**Issue by jemag** [stevearc/aerial.nvim#329]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-cdc8bac

### Operating system/version

Arch Linux 6.6.1-arch1-1

### Output of :AerialInfo

Using minimal `repro.lua` on go file:
Aerial Info
-----------
Filetype: go
Configured backends:
  treesitter (supported) (attached)
  lsp (not supported) [No LSP client found that supports symbols]
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct

### Describe the bug

The highlight `AerialLine` does not seem to take precedence over other highlight groups. For example, `AerialFunction` foreground color will be used instead of the one defined by `AerialLine`

### Steps To Reproduce

1. Open example file with minimal config using `nvim -u repro.lua main.go`
2. Notice that despite that AerialLine highlight defining `black` foreground, the color remains white:
![image](https://github.com/stevearc/aerial.nvim/assets/7985687/7fbfdd35-1226-4ae6-9da6-75ed3c5f7b60)
![image](https://github.com/stevearc/aerial.nvim/assets/7985687/c2e880bb-d8fa-4876-9fe0-ac3a56b1c712)
![image](https://github.com/stevearc/aerial.nvim/assets/7985687/44defad8-9c31-41d5-863f-2fc56d342292)
![image](https://github.com/stevearc/aerial.nvim/assets/7985687/bab291d3-268d-4960-9a2d-0eadf4cc37da)

3. Notice that `AerialFunction` seems to take precedence over `AerialLine` foreground
![image](https://github.com/stevearc/aerial.nvim/assets/7985687/cb5b6ea0-ad9f-4806-941f-d05703c289b1)

### Expected Behavior

`AerialLine` highlight takes precedence

### Minimal example file

package main

import "fmt"	

func main() {
    fmt.Println("hello world")
}

func other() {
}
func other1() {
}
func other2() {
}

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "Shatur95/neovim-ayu",
  {
    "nvim-treesitter/nvim-treesitter",
    config = function()
      require("nvim-treesitter.configs").setup({
        indent = {
          enable = false,
        },
        highlight = {
          enable = true, -- false will disable the whole extension
        },
        ensure_installed = {
          "go",
        }, -- one of "all", "language", or a list of languages
      })
    end,
  },
  {
    "stevearc/aerial.nvim",
    config = function()
      vim.g.mapleader = " "
      require("aerial").setup({
        layout = {
          min_width = 25,
        },
        on_attach = function(bufnr)
          -- Toggle the aerial window with <leader>a
          -- Jump forwards/backwards with '{' and '}'
          vim.api.nvim_buf_set_keymap(bufnr, "n", "{", "<cmd>AerialPrev<CR>", { desc = "Aerial prev" })
          vim.api.nvim_buf_set_keymap(bufnr, "n", "}", "<cmd>AerialNext<CR>", { desc = "Aerial prev" })
          -- Jump up the tree with '[[' or ']]'
          vim.api.nvim_buf_set_keymap(bufnr, "n", "[[", ":lua require('aerial').prev_up()<CR>", { desc = "Aerial prev up" })
          vim.api.nvim_buf_set_keymap(bufnr, "n", "]]", ":lua require('aerial').next_up()<CR>", { desc = "Aerial next up" })
        end,
      })
      vim.keymap.set("n", "<leader>ta", "<cmd>AerialToggle!<CR>", { desc = "Toggle aerial" })
      vim.api.nvim_create_autocmd({ "ColorScheme" }, {
        pattern = "*",
        callback = function()
          -- vim.api.nvim_set_hl(0, "AerialFunction", { link = "Normal" })
          vim.api.nvim_set_hl(0, "AerialLine", { fg = "black", bg = "#D4BFFF", force = true })
        end,
      })
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("ayu-mirage")
```

**Comment by stevearc** [comment]
fixed!
