### ISSUE TITLE
bug: "AerialOpen float" is always empty, but "left" and "right" work

### ISSUE THREAD

**Issue by Hubro** [stevearc/aerial.nvim#331]
### Neovim version (nvim -v)

v0.10.0-dev-d2e7cc6

(Just tested v0.9.4 and it works, so it's specifically an issue with nightly)

### Operating system/version

NixOS 23.11

### Output of :AerialInfo

```
Aerial Info
-----------
Filetype: python
Configured backends:
  treesitter (supported) (attached)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```

### Describe the bug

`AerialOpen left` and `AerialOpen right` always work, but `AerialOpen float` is always empty:

![image](https://github.com/stevearc/aerial.nvim/assets/597206/c80edeb0-f1bf-4cf3-ad1f-b8600b7f5d84)

![image](https://github.com/stevearc/aerial.nvim/assets/597206/904629aa-6f84-45a5-b999-bc78e676915b)

The first time I run `AerialOpen float` in a Neovim session, it shows "Loading", but nothing ever happens:

![image](https://github.com/stevearc/aerial.nvim/assets/597206/030d242f-34c3-4383-ab45-7a639773c738)

If I reopen it, it's an empty window like above.

### Steps To Reproduce

1. Open any document supported by Aerial
1. Run `:AerialOpen float`
1. See empty floating window, no visible error messages

### Expected Behavior

Should have the same content as `:AerialOpen left/right`

### Minimal example file

```python
class Foo:
    def foo():
        pass

    def bar():
        pass
```

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/aerial.nvim",
    config = function()
      require("aerial").setup({
        -- add your aerial config here
      })
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "c", "lua" },
        auto_install = true,
        highlight = { enable = true },
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

Result:

![image](https://github.com/stevearc/aerial.nvim/assets/597206/36bd7362-da26-458c-b7de-0f84fa128064)

### Additional context

Tried with and without my Aerial config, didn't make a difference.

`:AerialNavOpen` works, so the only thing that doesn't work is `:AerialOpen float`, which is my preferred use case :smile:

**Comment by Hubro** [comment]
I just updated my nightly build to `v0.10.0-dev-b32b5b2` and it's still broken, but then I tried downloading the official nightly AppImage (`v0.10.0-dev-1731+g0bbe8e7fc`) and there it works :confused: 

So it seems to only be broken in my nightly builds from [neovim-nightly-overlay](https://github.com/nix-community/neovim-nightly-overlay) for some reason. Very strange. Sorry for the noise!

**Comment by Hubro** [comment]
Hold on, now it's broken in the nightly appimage too. Demonstration:

Neovim 0.9.4 and 0.9.5:

![image](https://github.com/stevearc/aerial.nvim/assets/597206/95d5ce08-513f-49da-b53f-35e4edea05d7)

Neovim v0.10.0-dev-2129+gba9f86a9c (nightly appimage):

![image](https://github.com/stevearc/aerial.nvim/assets/597206/7ddccb29-7cb4-4fbc-b702-4e6953ae10ee)

Symptoms are all as initially described.

**Comment by stevearc** [comment]
I found two bugs. One of them was easy to fix, the other one I have filed upstream https://github.com/neovim/neovim/issues/27121

**Comment by b0o** [comment]
In case it's helpful to anyone, I'm using this workaround until the bug is fixed upstream:
```lua
vim.keymap.set('n', '<leader>af', function()
  vim.cmd.AerialOpen 'float'
  -- NOTE: Workaround for https://github.com/stevearc/aerial.nvim/issues/331
  vim.cmd.doautocmd 'BufWinEnter'
end)
```

**Comment by stevearc** [comment]
This appears to be fixed upstream now. Can you try it again on the most recent nightly?

**Comment by b0o** [comment]
> This appears to be fixed upstream now. Can you try it again on the most recent nightly?

Works for me now without manually triggering the autocommand, but I still need to do refetch_symbols first or else the symbols might be stale. Not sure if that is the same issue or not.

**Comment by stevearc** [comment]
When you say the symbols might be stale, what problem does this manifest as? Like if you've recently added a symbol it may not be present? Or there won't be any symbols? And is this sporadic or does it happen every time for you?

**Comment by b0o** [comment]
> Like if you've recently added a symbol it may not be present

Yes, after I open Aerial for the first time, the symbols won't update as I add/remove them in the buffer until I call refetch_symbols.

I just checked my config and switching from `backends = { 'lsp', 'treesitter', 'markdown', 'man' }` to `backends = { 'treesitter', 'lsp', 'markdown', 'man' }` seems to have fixed that issue.

**Comment by stevearc** [comment]
Hmmm...this sounds like it might be related to the specific LSP server. Does this happen with other LSP servers? Another thing you can try is setting the config value `lsp.diagnostics_trigger_update = false`. That should be more reliable about updating your symbols.

Also, does this only happen for `:AerialOpen float`, or does it also happen for `:AerialOpen left`?

**Comment by b0o** [comment]
>  Does this happen with other LSP servers? 

It happens with both tsserver and lua_ls. Not sure about others.

> Also, does this only happen for :AerialOpen float, or does it also happen for :AerialOpen left?

It happens with both.

> Another thing you can try is setting the config value `lsp.diagnostics_trigger_update = false`

That works!

**Comment by stevearc** [comment]
If `lsp.diagnostics_trigger_update = false` fixes the problem, then it's probably just an issue with our interaction with the LSP diagnostics as a trigger to re-fetch symbols. I'll mark this issue as closed now and look into making that config option the default.
