### ISSUE TITLE
Configuration help

### ISSUE THREAD

**Issue by RaZ0rr-Two** [stevearc/aerial.nvim#34]
I am having trouble with setting up aerial.

If I have default lspconfig like this

```lua
local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  -- Enable completion triggered by <c-x><c-o>
  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }

  -- See `:help vim.lsp.*` for documentation on any of the below functions
  buf_set_keymap('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<CR>', opts)
  buf_set_keymap('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', opts)
  buf_set_keymap('n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
  -- other keybindings ...

end
```
do I configure aerial like this ?
```lua
local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  -- Enable completion triggered by <c-x><c-o>
  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }

  -- See `:help vim.lsp.*` for documentation on any of the below functions
  buf_set_keymap('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<CR>', opts)
  buf_set_keymap('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', opts)
  buf_set_keymap('n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
  -- other keybindings ...

  require'aerial'.on_attach()

end
```
I am not able to get both working together.

**Comment by stevearc** [comment]
That is correct, though technically you should pass through the `client` and `bufnr` arguments. When you say you're not able to get them working together, what is the actual behavior you are observing? Also, what version of neovim are you on and can you open a file that you expect aerial to work for and paste the output of `:AerialInfo`?

**Comment by RayZ0rr** [comment]
Thank you!

adding `require'aerial'.on_attach(client, bufnr)` fixed the issue.

However, in the readme in [this section](https://github.com/stevearc/aerial.nvim#lsp), shouldn't it be `on_attach = require'aerial'.on_attach,`

**Comment by stevearc** [comment]
Yeah, I can update that section 👍

**Comment by motorto** [comment]
Hey sorry to comment on a closed issue @stevearc, but I have aeriel configured the same way but today I updated all the plugins and I get the following error: 

![image](https://user-images.githubusercontent.com/52639805/148269089-d7745f3c-62d5-4ba6-9eb4-015826b6289e.png)
```
	local on_attach = function(client, bufnr)
		require "lsp_signature".on_attach()

		local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
		local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end


		-- Enable completion triggered by <c-x><c-o>
		buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

		-- Mappings.
		local opts = { noremap=true, silent=true }

		-- See `:help vim.lsp.*` for documentation on any of the below functions
		buf_set_keymap('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<CR>', opts)
                -- other keymaps ...

		require("aerial").on_attach(client, bufnr)
	end
```

Am I doing something wrong ?

**Comment by stevearc** [comment]
Somewhere in your config you are calling `require("aerial").register_attach_cb()`, likely to set up keybindings. Instead of that, you should pass that function in to the setup() call:
```lua
require("aerial").setup({
  on_attach = function(bufnr)
    -- set keymaps, etc
  end,
})
```

**Comment by motorto** [comment]
> Somewhere in your config you are calling `require("aerial").register_attach_cb()`,

You are right ... Thanks missed that part. Thanks for the quick answer :)

**Comment by stevearc** [comment]
Sure no worries!
