### ISSUE TITLE
[Ruby] "Number is not integral" error in RSpec file

### ISSUE THREAD

**Issue by olimorris** [stevearc/aerial.nvim#35]
**Describe the bug**
Triggering `AerialToggle` on a Ruby RSpec file causes an error in `aerial/util.lua`:

```
E5108: Error executing lua ...vim/site/pack/packer/opt/aerial.nvim/lua/aerial/util.lua:54: Number is not integral stack traceback:
        [C]: in function 'nvim_win_set_width'
        ...vim/site/pack/packer/opt/aerial.nvim/lua/aerial/util.lua:54: in function 'set_win_width'
        ...m/site/pack/packer/opt/aerial.nvim/lua/aerial/window.lua:107: in function 'create_aerial_window'
        ...m/site/pack/packer/opt/aerial.nvim/lua/aerial/window.lua:168: in function 'open'
        ...m/site/pack/packer/opt/aerial.nvim/lua/aerial/window.lua:200: in function 'toggle'
        [string "luaeval()"]:1: in main chunk
```

**System information**
- OS: macOS 12.1
- Neovim version: 0.6.0
- AerialInfo:
```
Filetype: ruby
Configured backends:
  lsp (not supported)
  treesitter (supported) (attached)
  markdown (not supported)
Show symbols: Class, Constructor, Enum, Function, Interface, Method, Struct
```

**To Reproduce**
1. Open the following file, `zeitwork_spec.rb` in Neovim, with `aerial.nvim` installed:
```ruby
describe "Zeitwerk" do
  it "eager loads all files" do
    expect { Zeitwerk::Loader.eager_load_all }.not_to raise_error
  end
end
```
2. Run `AerialToggle`

**Other Points to Note**
`aerial.nvim` works perfectly on other Ruby files, such as:
```ruby
class MyController < ActionController::API
  def index; end

  def create; end

  def show; end
end
```
and produces the following output:
![Screen Shot 2021-12-29 at 12 22 48@2x](https://user-images.githubusercontent.com/9512444/147661737-23e5f0a2-3ad7-4c4e-b5aa-3a4d07fd1fa5.png)

**Comment by olimorris** [comment]
Appreciate this maybe functionality you do not wish to add however maybe if we could handle the error gracefully?

**Comment by stevearc** [comment]
Found the issue. Thanks for the report! The error should be fixed now. Note that Rspec files may not have any symbols in the Aerial window because `describe` and `it` are function *calls*, not function *definitions*. That is functionality that could probably be added; if you want that behavior go ahead and open another issue for it.
