### ISSUE TITLE
feature request: autofocus while toggle

### ISSUE THREAD

**Issue by onns** [stevearc/aerial.nvim#364]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

mostly, toggling   means I want to see the outline or jump to another function. It would be nice to automatically focus on it so I do not need to switch window.

### What is the significance of this feature?

strongly desired

**Comment by stevearc** [comment]
`:AerialOpen` or `:AerialToggle` automatically place the cursor in the aerial window. How are you toggling Aerial and can you reproduce the issue with a minimal neovim config?

**Comment by onns** [comment]
> `:AerialOpen` or `:AerialToggle` automatically place the cursor in the aerial window. How are you toggling Aerial and can you reproduce the issue with a minimal neovim config?

Sorry, I wrote the wrong config without following the guide.

`With ! cursor stays in current window`

```lua
{
        'stevearc/aerial.nvim',
        opts = {},
        -- Optional dependencies
        dependencies = {
            "nvim-treesitter/nvim-treesitter",
            "nvim-tree/nvim-web-devicons"
        },
        keys = {
            {
                "<leader>t",
                "<cmd>AerialToggle!<cr>",
                desc = "AerialToggle"
            }
        }
    },
```
![image](https://github.com/stevearc/aerial.nvim/assets/16622934/436e05bc-1ae7-4aeb-8e44-a8c8c734cb05)

Remove the **!** and that's what I expect.
