### ISSUE TITLE
How do you prevent the Aerial split pane from becoming a buffer when the cursor is inside?

### ISSUE THREAD

**Issue by niamleeson** [stevearc/aerial.nvim#372]
I often accidentally leave the cursor inside the Aerial split pane and switch to a different buffer and the pane ends up becoming that buffer. How do I prevent this from happening?

**Comment by stevearc** [comment]
Check out https://github.com/stevearc/stickybuf.nvim/ 
Or if you're on Neovim 0.10+, you can set `winfixbuf` on the aerial window

**Comment by magras** [comment]
@stevearc, with the release of 0.10 does it make sense to set `winfixbuf` automatically in aerial?
