### ISSUE TITLE
Not playing well with rmagatti/goto-preview

### ISSUE THREAD

**Issue by joehannes** [stevearc/aerial.nvim#38]
**Describe the bug**
[I initially reported it with goto-preview, but rmagatti was thinking maybe its due to aerial ...](https://github.com/rmagatti/goto-preview/issues/56)

**System information**
- OS: [windows/linux/mac] mac
- Neovim version:0.7 nightly (v0.7.0-dev+2267-gc46f7caad)
- AerialInfo: [output of :AerialInfo]
Aerial Info
-----------
Filetype: typescriptreact
Configured backends:
  lsp (supported) (attached)
  treesitter (not supported)
Show symbols: all symbols

**To Reproduce**
1.  install goto-preview alongside aerial (or use my setup github.com/joehannes-os/neovim-lua-setup
2. use default goto-preview shortcut to preview definition of a thing in a floating window "gpd" in normal mode with cursor on the thing (eg.: a React Component var ... but not the definition, haha)
3. see it fail with an aerial error msg

If possible, provide a minimal file that will trigger the issue:
```
sorry ...
```

**Screenshots**
![8089FD12-9F1F-45C4-96A1-CC9A56702B78](https://user-images.githubusercontent.com/63741107/147795449-059ea261-295c-4832-acf9-9717da501f47.png)

**Additional context**

**Comment by stevearc** [comment]
I couldn't get goto-preview working to repro, so I'm just taking a stab here. I pushed up a change that should hopefully fix the crash. From the trace, it seems like we're getting a LSP symbols callback on a buffer that's invalid (usually means it's been deleted). Not sure why that would happen, but we can guard against it pretty easily. Give the update a try and let me know if that helps

**Comment by joehannes** [comment]
yeah @stevearc :-) ... that actually solved the issue!!

![C8A79F60-02CF-44A2-BB4F-2D8861EDFA81](https://user-images.githubusercontent.com/63741107/147800446-f15437fd-7be8-488d-b6ff-0be94f5325d2.png)

hurray
