### ISSUE TITLE
Feature request: tree-like hierarchy ascii

### ISSUE THREAD

**Issue by knpwrs** [stevearc/aerial.nvim#41]
Consider this truncated output from running `tree lib` in https://github.com/knpwrs/dotfiles:

```
❯ tree lib
lib
├── snm.zsh
├── spell
│   ├── en.utf-8.add
│   ├── en.utf-8.add.spl
│   └── sort.sh
├── starship.zsh
├── sublime.zsh
├── terminal.app.zsh
├── terraform.zsh
├── tmux.zsh
├── transfer.zsh
├── yarn.zsh
└── zoxide.zsh
```

It would be great to have those branch ascii art things in Aerial so it would be easier to see the hierarchy.

**Comment by stevearc** [comment]
Sounds reasonable. You can now set `show_guides = true` in your setup() call to enable those symbols. Let me know if there are any edge cases where the display doesn't look right

**Comment by axieax** [comment]
Hi, sorry for bumping this issue, but would it be possible to add a bit more spacing between the end of the guide lines and the start of the icon (like nvim-tree)? Similarly, would it be possible to change the colour of the guide lines as well :)

![image](https://user-images.githubusercontent.com/62098008/151670157-d6b50ee2-facb-44db-a48a-23f74064d329.png)

**Comment by stevearc** [comment]
Added highlight groups and config options to allow you to customize the guide
display. If you want it to look like nvim-tree, you should use:
```lua
require('aerial').setup({
  show_guides = true,
  guides = {
    mid_item = "│ ",
    last_item = "└ ",
  },
})
```

**Comment by axieax** [comment]
Thanks for the quick changes as always <3
