### ISSUE TITLE
add Julia language

### ISSUE THREAD

**Issue by ExpandingMan** [stevearc/aerial.nvim#42]
**Language**: Julia

```julia
module M

const X = nothing  # global const

function f()  # function
end

g() = nothing  # single line function

abstract type A end

struct B <: A
    B() = new()  # inner constructor
end

end
```

Hi, it seems that the tree-sitter back-end is working reliably now, and I'm interested in using this package.  Personally, I'm only interested in the tree-sitter back-end, but there are some Julia users who use LSP in nvim, so there may be interest in that as well.

**Comment by stevearc** [comment]
Tree-sitter support added! I'm wholly unfamiliar with Julia, so I expect it'll need some tweaks as you use it on actual code. Just post any incorrect cases here or in a new issue.

For anyone using the LSP backend, it should already Just Work. That's the main advantage of LSP as a standardized protocol.

**Comment by ExpandingMan** [comment]
Cool, thanks!  I'll test it out when I get a chance and let you know how it goes.

**Comment by ExpandingMan** [comment]
This seems to mostly work.

The only issue I have noticed is that sometimes the presence of splatted arguments seems to screw up the entire list, but this seems to be intermittent.  (Splatted arguments are iterables expanded into multiple arguments, e.g. like `f(*x)` in Python.)  I cannot reliably reproduce this, and it does not seem to be a problem in my template.  It could be an issue with treesitter, I have no reason to believe it is specific to aerial.

Anyway, I have also updated the template with a `macro`, which I forgot the first time.
```julia
module M

const X = nothing  # global const

function f(a...; kw...)  # function
end

g() = nothing  # single line function

abstract type A end

struct B <: A
    B() = new()  # inner constructor
end

macro mac(expr)
end

end
```
If you could update this with `macro`, then perhaps we should close this issue, and I can open another when I figure out an MWE for whatever is happening with spaltting.

Thanks for your help!

**Comment by stevearc** [comment]
Sounds good! What LSP type would you like the macro to appear as (this only affects the icons). For the moment we're tied to LSP SymbolKind, and it doesn't have an option for Macro. Function? Method? Full list here: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#symbolKind

**Comment by ExpandingMan** [comment]
Wow, it's really weird that that list is so small... it would probably belong in some kind of pre-processing block or something, but they don't even have such an option.  I guess there's not choice other than `Function` 🤷

**Comment by stevearc** [comment]
Macro support added

**Comment by ExpandingMan** [comment]
Great, thanks!
