### ISSUE TITLE
Support for Djot

### ISSUE THREAD

**Issue by calebeby** [stevearc/aerial.nvim#433]
**Language**: [Djot](https://github.com/jgm/djot) (like markdown)

Syntax description: https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html

More about Djot (and why it exists) here: https://johnmacfarlane.net/beyond-markdown.html

Here is the treesitter for it: https://github.com/treeman/tree-sitter-djot

Test code (same as markdown but without the underline-style headings)

````
# Title 1

## Title 2

# Title 3

### Title 4

```
# Nope
```

#### Title 5

contents

```
Nope
----
```
````

**Comment by calebeby** [comment]
BTW I couldn't find in the docs for this plugin any way to override/pass my own TS query in, but if there is, I'd be happy to do that.

**Comment by stevearc** [comment]
Turns out it was pretty easy to add support!

**Comment by calebeby** [comment]
Thanks :tada:
