### ISSUE TITLE
Error when file contains too many symbols

### ISSUE THREAD

**Issue by levouh** [stevearc/aerial.nvim#45]
**Describe the bug**
See screenshot below:

![image](https://user-images.githubusercontent.com/31262046/148815814-e11ac3e8-c9c4-40fd-854e-78c7bed09666.png)

**System information**
- OS: Linux
- Neovim version: `NVIM v0.7.0-dev+863-g8f27c4a04`
- AerialInfo:
```
Aerial Info                                                                                                                                                                      
-----------
Filetype: lua
Configured backends:
  lsp (supported) (attached)
  treesitter (supported)
  markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Method, Struct
```

This is a bit mis-leading as the error is happening in a work environment where I cannot copy/paste from easily.

**To Reproduce**
1. Run `:AerialToggle` in a file with a large number of symbols

Not a minimal configuration, however this is what I use:
```
  require("aerial").setup({
    close_behavior = "close",
    default_bindings = true,
    default_direction = "float",
    diagnostics_trigger_update = true,
    highlight_mode = "split_width",
    highlight_on_jump = 300,
    link_tree_to_folds = true,
    link_folds_to_tree = false,
    manage_folds = "auto",
    max_width = 40,
    min_width = 10,
    nerd_font = "auto",
    open_automatic = false,
    post_jump_cmd = "normal! zz",
    close_on_select = true,
    update_when_errors = true,
    float = {
      max_height = 500,
      min_height = 4,
    },
    filter_kind = {
      "Class",
      "Constructor",
      "Enum",
      "Function",
      "Interface",
      "Method",
      "Struct",
    },
    icons = {
      Class = "",
      ClassCollapsed = "",
      Function = "",
      Constant = "",
      Collapsed = "▶",
    },
  })

```

**Screenshots**
See above.

**Additional context**
I will add some debug logs and attempt to figure out what the arguments that it is passing to open the floating window are, versus the actual size of the window itself.

**Comment by levouh** [comment]
@stevearc as noted above, I will debug a bit later and try to add more information. Just reporting for now before I forget; followup will be in a few hours after work.

**Comment by stevearc** [comment]
Should be fixed now. I think it was just a simple error where a divide-by-2 led us to passing in a float to an API that only takes ints.

**Comment by levouh** [comment]
Awesome, will verify in a bit. Thanks.

**Comment by levouh** [comment]
Works for me, thanks for the fix.
