### ISSUE TITLE
[Statusline Component] symbols persist when the cursor does not have a symbol(blank line)

### ISSUE THREAD

**Issue by Lopi-py** [stevearc/aerial.nvim#52]
**Describe the bug**
Basically for example, in lua when I create a function and I move the cursor inside to the function, the statusline component updates and show the function name, but if I move the cursor outside to the function, the statusline isn't updated.

**System information**
- OS: `Windows`
- Neovim version: `NVIM v0.7.0-dev+922-g1b6ae2dbb`
- AerialInfo: 
```
Aerial Info
-----------
Filetype: lua
Configured backends:
  lsp (supported) (attached)
  treesitter (supported)
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```
- Aerial config:
```lua
require("aerial").setup({
    backends = { "lsp", "treesitter" },
    open_automatic = true,
    max_width = 30,
    min_width = 30,
})
```

**To Reproduce**
1. Just use the lualine component

If possible, provide a minimal file that will trigger the issue:
```lua
--------------------------

local function test()
    -- content
end

--------------------------
```

**Screenshots**
https://gyazo.com/3f8e39591f46af5a331e964a99015417
when the cursor is in a blank line(or comment), statusline component shouldn't show `<Anonymous>`

**Comment by stevearc** [comment]
Unfortunately with just the symbols API there is not enough data to get the resolution that you're looking for. The LSP API, for example, will tell us where a function is defined but not the overall bounds of that function. This means that we can't handle cases like this:
```
function f1()
  -- pass
end
-- If the cursor is here all we know is that we're *after* f1 and *before* f2
function f2()
  -- pass
end
```

I see that you're using nvim-treesitter; you should consider looking at https://github.com/SmiteshP/nvim-gps to see if it better suits your needs

**Comment by Lopi-py** [comment]
Thanks, but I like aerial because give me more precise information, how vscode implements this https://gyazo.com/a90270e1dfe30d60ea62282eea419143?, I'm pretty sure it's using the lsp.

**Comment by stevearc** [comment]
You are correct! I thought I knew what information was in this LSP call but I was wrong. I have pushed up a change that should do what you want, but the catch is that, for now, it only works with the LSP backend. I plan to change the treesitter backend to support it too, but that will take a lot more time. Will happen gradually over the next week or so.

**Comment by Lopi-py** [comment]
Thanks, it works fine, I'll also wait for treesitter backend being supported, Also could you add an option to choose if aerial window should disable cursorline if the cursor is on a blank line?
![image](https://user-images.githubusercontent.com/70210066/152094190-36e89165-c430-4ffb-a647-a787a2c12dc4.png)

**Comment by stevearc** [comment]
You can now set the config option `highlight_closest = false`

**Comment by Lopi-py** [comment]
Thanks!

**Comment by stevearc** [comment]
The treesitter and markdown backends now support this as well
