### ISSUE TITLE
Aerial forces pane height on opening

### ISSUE THREAD

**Issue by drusmanbashir** [stevearc/aerial.nvim#53]
Hi this issue happens when I have 2 panes open with a horizontal split. If one pane is taller than the other and I open aerial, it forces both panes to assume the same height.

I hope this explains itself and if not happy to provide a gif of the issue

Thanks a lot for the great plugin btw!

**Comment by stevearc** [comment]
Should be fixed. I was doing a `wincmd` that I don't believe is necessary anymore. If this causes odd window layout for anyone, please comment here
