### ISSUE TITLE
Aerial not updating

### ISSUE THREAD

**Issue by Lopi-py** [stevearc/aerial.nvim#54]
**Describe the bug**
Aerial is not updating(with sumneko_lua, pyright does works) the window

**System information**
- OS: `Windows`
- Neovim version: `NVIM v0.7.0-dev+991-g547497b04`
- AerialInfo:
```
Aerial Info
-----------
Filetype: lua
Configured backends:
  lsp (supported) (attached)
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```
- Aerial config:
```lua
require("aerial").setup({
    backends = { "lsp" },--"treesitter" },
    default_direction = "right",
    open_automatic = true,
    max_width = 30,
    min_width = 30,
})
```

**To Reproduce**
1. Wait for sumneko lua loaded.
2. `:AerialOpen`
3. write a new local function

**Screenshots**
https://gyazo.com/a50d37cea472bd3d78c174ba18b25607

**Aditional Context**
maybe it's a sumneko_lua problem, but I'm not sure

**Comment by stevearc** [comment]
I can't repro the issue with my LSP setup. By default aerial should update when the LSP diagnostics come in. There's a couple possibilities:
1. You're not getting diagnostics callbacks
2. You're getting the callbacks but aerial isn't fetching new symbols
3. You're fetching new symbols but they either don't return a result or return the incorrect result

You can test for 1 & 2 pretty easily by adding some debug print statements around here: https://github.com/stevearc/aerial.nvim/blob/fb6bbaaceebd2172112dc4ebccc88ee4084d930c/lua/aerial/backends/lsp/callbacks.lua#L122-L129
This is the function that handles diagnostics callbacks and does an early-return if aerial should *NOT* update the symbols

If there's no issue there then you can check for 3 by adding some print statements to the symbols callback https://github.com/stevearc/aerial.nvim/blob/fb6bbaaceebd2172112dc4ebccc88ee4084d930c/lua/aerial/backends/lsp/callbacks.lua#L91

**Comment by Lopi-py** [comment]
Oh right, I have diagnostics disabled since I use `selene` to get diagnostics, how I can update aerial manually?, I'm not seeing an option to update aerial

**Comment by stevearc** [comment]
It happens automatically when you update symbols (`vim.lsp.buf.document_symbol()`). You can use the option
```lua
require('aerial').setup({
  lsp = {
    diagnostics_trigger_update = false,
  }
})
```

I just pushed an update that will make it watch the buffer for changes if this
value is false. Previously it was up to the user to decide when to call `vim.lsp.buf.document_symbol()`, but since that option was put in I've added change watching utilities so it makes more sense to keep the logic inside aerial.

**Comment by Lopi-py** [comment]
Thanks!
