### ISSUE TITLE
New markdown file causes error on nil value.

### ISSUE THREAD

**Issue by fullstopslash** [stevearc/aerial.nvim#55]
**Describe the bug**
Aerial drops this error when a new markdown file has **no** symbols yet. 

Error executing vim.schedule lua callback: ...erial.nvim/lua/aerial/backends/treesitter/extensi
ons.lua:49: attempt to index local 'prev' (a nil value)
stack traceback:
        ...erial.nvim/lua/aerial/backends/treesitter/extensions.lua:49: in function 'set_end_ra
nge'
        ...erial.nvim/lua/aerial/backends/treesitter/extensions.lua:74: in function 'postproces
s_symbols'
        .../packer/opt/aerial.nvim/lua/aerial/backends/markdown.lua:51: in function 'fetch_symb
ols'
        ...pack/packer/opt/aerial.nvim/lua/aerial/backends/util.lua:41: in function 'cb'
        vim.lua:291: in function <vim.lua:291>

**System information**
- OS: [mac]
- Neovim version:
- AerialInfo: [output of :AerialInfo]
- Aerial config:
```lua
-- Paste your call to require("aerial").setup(...) in here
      "stevearc/aerial.nvim",                                    
      event = "BufReadPost",                                     
      config = function()                                        
         require("aerial").setup {                               
            backends = {                                         
               -- use underscore to specify the default behavior 
               ["_"] = { "lsp", "treesitter", "markdown" },      
               ["vimwiki.markdown.pandoc"] = { "treesitter" },   
               python = { "treesitter" },                        
               rust = { "lsp" },                                 
            },                                                   
            show_guides = true,                                  
            default_direction = "prefer_left",                   
            open_automatic = false,                                                      
         }                                                       
      end,                                                       


```

**Comment by stevearc** [comment]
Fixed! Thanks for the report
