### ISSUE TITLE
Latest merge causes a fatal issue

### ISSUE THREAD

**Issue by yanzhang0219** [stevearc/aerial.nvim#61]
Updated just now and have this issue that make Neovim totally unusable. 
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/11582667/154894335-de71d584-648e-4f45-ac80-ff228c76346c.png">

**Comment by stevearc** [comment]
I think I fixed the issue. Out of curiosity, are you on neovim nightly? I didn't see the error using v0.6.1

**Comment by yanzhang0219** [comment]
> are you on neovim nightly?

Yes, the latest master. 

I am so sorry I didn't follow the template when reporting this issue because it is desperate.

**Comment by yanzhang0219** [comment]
> I think I fixed the issue

Got another issue 

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/11582667/154896120-3968941c-c52e-442b-89fa-491e815492fa.png">

Thanks.

**Comment by yanzhang0219** [comment]
Yes. It is fixed. Thank you and I will close this.

**Comment by stevearc** [comment]
No worries! That error should be fixed now as well. Nightly added some stricter type checking to values crossing the lua->vim boundary, so some previously invisible bad calls are now showing up.

BTW most plugin managers have some way to pin to an earlier version, in case you need to roll back. For minpac, it looks like that would be `rev`.

**Comment by yanzhang0219** [comment]
Thanks a lot 👍

**Comment by b0o** [comment]
Aah, my bad for this one. Sorry @yanzhang0219

**Comment by yanzhang0219** [comment]
@b0o Hi, don't say sorry and instead I, as a user, should appreciate all the efforts you put into developing and implementing new features, and make this plugin more shining 👍 Thanks a lot.

**Comment by stevearc** [comment]
Y'all are so nice ♥️

This is why I like the Neovim community
