### ISSUE TITLE
Feature proposal: Highlight source buffer

### ISSUE THREAD

**Issue by b0o** [stevearc/aerial.nvim#65]
It would be very cool if the inverse of the current highlighting behavior were also possible: when the cursor is over an item in the aerial buffer, the corresponding line in the source buffer would be highlighted.

**Comment by stevearc** [comment]
Added a new option to enable this. Set `highlight_on_hover = true` and give it a shot!

**Comment by b0o** [comment]
Woah, that was super fast. It seems to be working perfectly, exactly as I envisioned. Thank you!
