### ISSUE TITLE
Disordered icon alignment when the vertical separator is set to the bar

### ISSUE THREAD

**Issue by rockyzhang24** [stevearc/aerial.nvim#66]
**Describe the bug**

After setting the vertical separator to the normal `<bar>` character via this `set fillchars=vert:\|` in `init.vim`, the vertical separator and the icons are disordered.

<img width="1728" alt="Screen Shot 2022-03-10 at 18 05 28" src="https://user-images.githubusercontent.com/11582667/157788364-a2b74b59-d169-4ffb-9919-8d6649338e0e.png">

See, the `bar` separators are placed between the icons and the symbol names. 

However, if I don't set the vertical separator, no issues there

<img width="1728" alt="Screen Shot 2022-03-10 at 18 12 59" src="https://user-images.githubusercontent.com/11582667/157788930-d1536aa8-286b-41c6-a681-aa5fe1359dd0.png">

**System information**
- OS: masOS 12.3
- Neovim version: NVIM v0.7.0-dev+1130-g11f7aeed7
- AerialInfo: 
```
Aerial Info                                                                                                                                                                                                
-----------                                                                                                                                                                                                
Filetype: vim                                                                                                                                                                                              
Configured backends:                                                                                                                                                                                       
  lsp (supported) (attached)                                                                                                                                                                               
  treesitter (supported)                                                                                                                                                                                   
  markdown (not supported) [Filetype is not markdown]                                                                                                                                                      
Show symbols: all symbols 
```
- Aerial config:
The default config. I only adjusted the key mappings.

**To Reproduce**
1. In `init.vim`, set `set fillchars=vert:\|`
2. Then in a buffer with lsp enabled, run `:AerialToggle!`

Thank you very much.

**Comment by stevearc** [comment]
Based on the screenshots, I think this is an unfortunate interaction between the patched font icons and your terminal. As a check, try replacing the out-of-order icon with `T` or some other basic character. If it displays as expected, then it's the icons.

I am no expert on terminals or font rendering, but my understanding of patched icon fonts is that they replace some range of characters outside the normal western set. Unfortunately, the characters they are replacing do have an actual purpose in unicode, and what's worse is that they can sometimes have unusual layout effects. Things like a zero-width space or [right-to-left override](https://unicode-table.com/en/202E/). I suspect that the unicode value for that particular icon has a non-normal layout and your terminal is trying to respect that, resulting in the weird display.

Some ideas for workarounds:
* Use a different icon for that symbol
* Try out a different value for fillchars vert (maybe `┃`?)
* Try a different terminal
* Put a space before the icon

**Comment by rockyzhang24** [comment]
Thank you so much for your quick response. I tried another terminal `iTerm2` and no issues there, so it is definitely caused by `kitty`, the terminal I am using. Hello @kovidgoyal, could you please take a look at this and see whether it can be solved on kitty's side. Please forgive me my offensive calling here. 

BTW,

> try replacing the out-of-order icon with T or some other basic character
> Use a different icon for that symbol
> Put a space before the icon

Stupid question here: how to change the icon? I tried many ways (like `icons = { Field = "T" }`) but failed. Btw, I have both `lspkind` and `devicon` plugins installed. 

Thanks a lot.

**Comment by stevearc** [comment]
If you have lspkind installed aerial will use that for icons. Change it with
```
require('lspkind').init({
  symbol_map = {
    Field = " ",
  }
})
```

**Comment by rockyzhang24** [comment]
Okay I got it. Thank you.

**Comment by rockyzhang24** [comment]
Thank you for the updates. Btw, I updated kitty to the latest version 0.25.2 and I found this issue was gone without setting `force_ltr yes`.

**Comment by stevearc** [comment]
Excellent!
