### ISSUE TITLE
 The golang neovim6.0 structure does not seem to be able to expand

### ISSUE THREAD

**Issue by j2501987804** [stevearc/aerial.nvim#71]
**Language**: [golang]
**AerialInfo**: [output of :AerialInfo]

The minimal amount of code that demonstrates the missing symbol:
```
[minimal code here]
```

**Expected symbol**: [Function/Class/Enum]
Try to use zo, the carriage return is invalid
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/41771911/160275826-eb64fcf7-cef0-48bd-9ca7-d808ce567166.png">

**Comment by stevearc** [comment]
You say that it doesn't expand, but it looks expanded to me? Is the problem that you can't close the fold?

What are your aerial settings?

What is the output of `:AerialInfo`?
