### ISSUE TITLE
Error: `textDocument/documentSymbol is not supported …` when switching focus from an LSP buffer to a TS buffer

### ISSUE THREAD

**Issue by b0o** [stevearc/aerial.nvim#78]
**Steps to reproduce**

1. Launch nvim and open a file which only has treesitter aerial support (a `ruby` file in my case)
2. Open a new split with a file that has LSP aerial support (a `javascript` file in my case)
3. Wait for the second file's LSP to attach
3. Re-focus the original window
4. The following error message is displayed:

```
method textDocument/documentSymbol is not supported by any of the servers registered for the current buffer
```

**Stack trace:**

```
/usr/share/nvim/runtime/lua/vim/lsp.lua:88: in function '_unsupported_method'
/usr/share/nvim/runtime/lua/vim/lsp.lua:1478: in function 'request'
/usr/share/nvim/runtime/lua/vim/lsp/buf.lua:323: in function 'document_symbol'
.../packer/opt/aerial.nvim/lua/aerial/backends/lsp/init.lua:54: in function 'fetch_symbols'
...er/opt/aerial.nvim/lua/aerial/backends/lsp/callbacks.lua:151: in function 'fn'
.../packer/opt/aerial.nvim/lua/aerial/backends/lsp/init.lua:14: in function <.../packer/opt/aerial.nvim/lua/aerial/backends/lsp/init.lua:10>
.../packer/opt/aerial.nvim/lua/aerial/backends/lsp/init.lua:31: in function 'handler'
/usr/share/nvim/runtime/lua/vim/lsp.lua:796: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Minimal reproducible configuration:**
```lua
require('aerial').setup {
  backends = { 'lsp', 'treesitter' },
}
```

The issue **does not** occur if `treesitter` comes before `lsp` in the `backends` list:

```lua
require('aerial').setup {
  backends = { 'treesitter', 'lsp' },
}
```

The issue **does** occur when the file without LSP aerial support is explicitly set only to `treesitter` if `lsp` comes before `treesitter` in the global order: 

```lua
require('aerial').setup {
  backends = {
    _ = { 'lsp', 'treesitter', 'markdown' },
    ruby = { 'treesitter' },
  },
}
```

**System information**

- OS: Arch Linux (`Linux 5.15.32-xanmod1-1 GNU/Linux`)
- Neovim version: `NVIM v0.7.0-dev+1294-g0c02e8a62` with `LuaJIT 2.1.0-beta3`
- `AerialInfo`: 

  On the `ruby` file:

  ```
  Aerial Info
  -----------
  Filetype: ruby
  Configured backends:
    lsp (not supported) [LSP client not attached]
    treesitter (supported) (attached)
    markdown (not supported) [Filetype is not markdown]
  Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct, Type
  ```

  On the `javascript` file:

  ```
  Aerial Info
  -----------
  Filetype: javascript
  Configured backends:
    lsp (supported) (attached)
    treesitter (supported)
    markdown (not supported) [Filetype is not markdown]
  Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct, Type
  ```

I have tested this with a few combinations of filetypes. It happens with all of them as long as the first file has only treesitter support and the other one has an LSP with `textDocument/documentSymbol` support.

**Comment by b0o** [comment]
Interestingly, the issue seems to stop happening after setting `lsp.diagnostics_trigger_update = false`.

**Comment by stevearc** [comment]
I didn't get a repro, but I didn't try very hard because I think I know what the issue is. If I'm correct, I think it should be fixed now. Give it a try?

**Comment by b0o** [comment]
Awesome, that seems to have fixed it. Thank you!
