### ISSUE TITLE
error on initialization: invalid node type

### ISSUE THREAD

**Issue by ExpandingMan** [stevearc/aerial.nvim#82]
**Describe the bug**
At startup
```
Error executing vim.schedule lua callback: ...dZ6x/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172
: query: invalid node type at position 109
stack traceback:
        [C]: in function '_ts_parse_query'
        ...dZ6x/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in function 'get_query'
        ...r/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:37: in function 'new'
        ...nvimgudZ6x/usr/share/nvim/runtime/lua/vim/treesitter.lua:46: in function '_create_parser'
        ...nvimgudZ6x/usr/share/nvim/runtime/lua/vim/treesitter.lua:94: in function 'get_parser'
        ...tart/aerial.nvim/lua/aerial/backends/treesitter/init.lua:37: in function 'fetch_symbols'
        ...tart/aerial.nvim/lua/aerial/backends/treesitter/init.lua:116: in function 'attach'
        ...ck/packer/start/aerial.nvim/lua/aerial/backends/init.lua:57: in function 'attach'
        ...ck/packer/start/aerial.nvim/lua/aerial/backends/init.lua:76: in function 'get'
        ...ck/packer/start/aerial.nvim/lua/aerial/backends/init.lua:129: in function 'attach'
        ...ack/packer/start/aerial.nvim/lua/aerial/autocommands.lua:28: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**System information**
- OS: Manjaro Linux
- Neovim version: `NVIM v0.7.0-dev+1453-g8486c87e5` `LuaJIT 2.1.0-beta3`

Features: +acl +iconv +tui

- AerialInfo: [output of :AerialInfo]
```
Aerial Info
-----------
Filetype:
Configured backends:
  treesitter (not supported) [No treesitter parser for ]
  markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Method, Struct
```

- Aerial config:
```lua
local Aerial = require("aerial")

Aerial.setup({
    backends = {"treesitter", "markdown"},
    close_behavior = "auto",
    default_bindings = true,
    default_direction = "prefer_right",
    filter_kind = {
        "Class",
        "Constructor",
        "Enum",
        "Function",
        "Interface",
        "Method",
        "Struct",
    },
    highlight_mode = "split_width",
    highlight_on_jump = 300,  -- time in ms to highlight after jumping
})
```

**To Reproduce**
Any time aerial.nvim initlializes.

**Comment by stevearc** [comment]
That's interesting, it looks like it's failing at `require("nvim-treesitter.parsers").get_parsers`. There have been a LOT of changes to the ecosystem recently. Would you mind:

1. Update to the stable 0.7.0 release of Nvim
2. Pull the latest aerial
3. If the error persists, can you give me the filetype of the buffer that's getting this error? For some reason it appears completely blank in the `:AerialInfo` output above.

**Comment by ExpandingMan** [comment]
Ok, I have tried this on 0.7 (as opposed to nightly which was what it was on before).  Problem looks the same.  Not sure why filetype didn't come up in my info before, but this is on `julia` (you may remember I had a request to add it not all that long ago which you graciously acted on 🙂 ).

So looks like something changed in the treesitter API which is currently breaking aerial in some edge cases.

**Comment by stevearc** [comment]
Yeah the API changes (at least, the ones I'm aware of) should be unrelated. I'm unfortunately not able to repro this myself, so I'll need some more information. First:
* Does this happen for all languages or just Julia?
* Does this repro for you on [julia_test.jl](https://github.com/stevearc/aerial.nvim/blob/master/tests/treesitter/julia_test.jl)? (That's the file I'm using to repro, so just want to make sure it triggers it for you)
* Could you post the stack trace that you're getting when on 0.7.0? The one in the initial issue has line numbers that don't match the function names on the commit I'm looking at.

One last thing to try: delete all the `.so` files under `nvim-treesitter/parser` and re-install them with `TSInstall`. I find that treesitter often breaks for me after I upgrade neovim, nvim-treesitter, or both, and this usually clears it up.

**Comment by gergol** [comment]
I have the same problem (with a slightly different error message though) with C++:

```
Error executing vim.schedule lua callback: ...sSWC/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:185: attempt to index local 'node' (a nil valu
e)
stack traceback:
        ...sSWC/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:185: in function 'get_node_text'
        ...erial.nvim/lua/aerial/backends/treesitter/extensions.lua:156: in function 'postprocess'
        ...gged/aerial.nvim/lua/aerial/backends/treesitter/init.lua:103: in function 'fetch_symbols'
        ...gged/aerial.nvim/lua/aerial/backends/treesitter/init.lua:124: in function 'attach'
        ...re/nvim/plugged/aerial.nvim/lua/aerial/backends/init.lua:57: in function 'attach'
        ...re/nvim/plugged/aerial.nvim/lua/aerial/backends/init.lua:76: in function 'get'
        ...re/nvim/plugged/aerial.nvim/lua/aerial/backends/init.lua:129: in function 'attach'
        ...are/nvim/plugged/aerial.nvim/lua/aerial/autocommands.lua:28: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

```

The error occurs not in every c++ file I've tested, but I was able to trace it down a bit and come up with a minimal reproducible example. Opening the following file in stable nvim 0.7 with a fresh PlugUpdate and freshly compiled treesitter parsers triggers the error here:

**test.hpp**
```
class Test
{
    ~Test()
    {
    }
};
```
As soon as the tilde is removed, the file works correctly. Hope, that helps a bit...

**Comment by stevearc** [comment]
I think that is a different error, but still valid! Thanks for the minimal repro, it made it super easy to track down. Should be fixed now.

**Comment by ExpandingMan** [comment]
It's only happening on Julia for me but I don't currently have treesitter set up on any other languages.

Here is the stack trace from the tagged 0.7.0
```
Error executing vim.schedule lua callback: ...yef6/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 109
stack traceback:
        [C]: in function '_ts_parse_query'
        ...yef6/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in function 'get_query'
        ...r/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:37: in function 'new'
        ...nvimYZyef6/usr/share/nvim/runtime/lua/vim/treesitter.lua:46: in function '_create_parser'
        ...nvimYZyef6/usr/share/nvim/runtime/lua/vim/treesitter.lua:94: in function 'get_parser'
        ...tart/aerial.nvim/lua/aerial/backends/treesitter/init.lua:45: in function 'fetch_symbols'
        ...tart/aerial.nvim/lua/aerial/backends/treesitter/init.lua:124: in function 'attach'
        ...ck/packer/start/aerial.nvim/lua/aerial/backends/init.lua:57: in function 'attach'
        ...ck/packer/start/aerial.nvim/lua/aerial/backends/init.lua:76: in function 'get'
        ...ck/packer/start/aerial.nvim/lua/aerial/backends/init.lua:129: in function 'attach'
        ...ack/packer/start/aerial.nvim/lua/aerial/autocommands.lua:28: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by ExpandingMan** [comment]
🤦 

Ugh, I'm an idiot!  I completely forgot that treesitter had its own binaries.  I'll have to set something up to update them automatically.

Thanks for helping track that down!

**Comment by gergol** [comment]
@stevearc I can confirm that the bug I reported is fixed now. Thank you very much!
