### ISSUE TITLE
Treesitter update and aerial failed

### ISSUE THREAD

**Issue by chen244** [stevearc/aerial.nvim#84]
https://github.com/nvim-treesitter/nvim-treesitter/commit/c3848e713a8272e524a7eabe9eb0897cf2d6932e
And you use this function in backends/treesitter, And it makes your code failed

**Comment by rockyzhang24** [comment]
Same here.

**Comment by stevearc** [comment]
Should be fixed now

**Comment by axieax** [comment]
Not sure why I sometimes get this error though:

```
E5108: Error executing lua .../pack/packer/start/aerial.nvim/lua/aerial/navigation.lua:216: Vim(let):E5100: Cannot convert gi
ven lua table: table should either have a sequence of positive integer keys or contain only string keys
stack traceback:
        [C]: in function 'nvim_set_current_win'
        .../pack/packer/start/aerial.nvim/lua/aerial/navigation.lua:216: in function 'select'
        ...m/site/pack/packer/start/aerial.nvim/lua/aerial/init.lua:92: in function 'select'
        [string ":lua"]:1: in main chunk
```

This happens when I try to navigate to [this function](https://github.com/axieax/dotconfig/blob/main/nvim/lua/axie/plugins/binds.lua#L314).

**Comment by rockyzhang24** [comment]
@stevearc Yes, it was fixed 👊. Now no errors. Thank you.
