### ISSUE TITLE
[Feature]: customizable kind icons

### ISSUE THREAD

**Issue by xeluxee** [stevearc/aerial.nvim#88]
**Describe the feature request**
At the moment kind icons are "hardcoded":
https://github.com/stevearc/aerial.nvim/blob/4dc21934fd2899380f53e19e3192020e832c3b20/lua/aerial/config.lua#L255-L283

But I think it'd be nice to have the possibility to customize kind icons and their highlight groups through `setup` function, as `symbols-outline.nvim` does
https://github.com/simrat39/symbols-outline.nvim#configuration

**Comment by stevearc** [comment]
You can actually already do this! Use the `icons` option. The symbols & text each have their own highlight groups, [as documented here](https://github.com/stevearc/aerial.nvim#highlight)

https://github.com/stevearc/aerial.nvim/blob/4dc21934fd2899380f53e19e3192020e832c3b20/lua/aerial/config.lua#L68-L73

**Comment by xeluxee** [comment]
My bad, I didn't noticed it 😅
Thanks
