### ISSUE TITLE
quick jump

### ISSUE THREAD

**Issue by y1rn** [stevearc/aerial.nvim#9]
can u add quick jump feature, such as fzf integration like vscode <s-c-o>, look's like more useful for keyboard

**Comment by stevearc** [comment]
I just added a telescope extension. Will that suit your needs?

**Comment by y1rn** [comment]
thx, i will try. but i prefer fzf, because fzf can use in command line and vim/neovim and i haven't been use telescope.

**Comment by stevearc** [comment]
Added fzf integration as well. Instructions here: https://github.com/stevearc/aerial.nvim#fuzzy-finding

**Comment by y1rn** [comment]
thx very much.  but collapse issue make me confuse, current buffer collapse all after first ```:call  aerial#fzf() ``` or  ```AerialToggle!``` or ```:e file```

**Comment by stevearc** [comment]
I just pushed up a change that should improve the default behavior. You can also change it yourself using `set foldlevelstart=99` (see `:help foldlevelstart` and `:help foldlevel` for more details).

**Comment by y1rn** [comment]
> I just pushed up a change that should improve the default behavior. You can also change it yourself using `set foldlevelstart=99` (see `:help foldlevelstart` and `:help foldlevel` for more details).

it work well, thx
