### ISSUE TITLE
Automatically close the aerial window when the corresponding buffer is closed

### ISSUE THREAD

**Issue by krishnakumarg1984** [stevearc/aerial.nvim#90]
**Description**
Let's say we open a buffer with some symbols and use aerial to open the symbol tree. When we close the original buffer (e.g. through `:bwipeout`, `:bdelete`, `<C-W> + c` etc, the aerial window should also close. For instance, it is expected that the aerial window shall auto-close when the last valid file/buffer is closed, and can be mildly surprising when just the aerial window persists as the last open buffer. 

Currently, the aerial window is left orphaned, pointing to dangling symbols which lead to a bunch of error lines when trying to open.
```
E5108: Error executing lua ...te/pack/packer/opt/aerial.nvim/lua/aerial/navigation.lua:175: Could not find destination window
stack traceback:
	[C]: in function 'error'
	...te/pack/packer/opt/aerial.nvim/lua/aerial/navigation.lua:175: in function 'select'
	...vim/site/pack/packer/opt/aerial.nvim/lua/aerial/init.lua:92: in function 'select'
	[string ":lua"]:1: in main chunk
```

**System information**
- OS: Linux
- Neovim version: 0.7
- AerialInfo: 
- Aerial Info
```
-----------
Filetype: lua
Configured backends:
  lsp (not supported) [LSP client not attached]
  treesitter (supported) (attached)
  markdown (not supported) [Filetype is not markdown]
Show symbols: Array, Boolean, Class, Constant, Constructor, Enum, EnumMember, Event, Field, File, Function, Interface, Key, Method, Module, Namespace, Null, Number, Object, Operator, Package, Property, String, Struct, TypeParameter, Variable
```
- Aerial config: N/A. Issue cccurs in the default config as well.

**To Reproduce**
1. Open any file with suitable symbols (functions, classes etc). e.g. a Lua config file for neovim
2. Toggle the symbols outline window with `:AerialToggle<CR>`
3. Close the original file with `:q` (or `ZZ`, `ZQ` etc). The aerial window alone will persist. 

**Screenshots**
![image](https://user-images.githubusercontent.com/15239509/166164266-a3af06eb-e20c-447b-8952-085be8425d69.png)

After `:q`, we are left with
![image](https://user-images.githubusercontent.com/15239509/166164299-c098856e-2a8b-4692-947d-00886365fd34.png)

And pressing `<CR>` on any of the symbols in the tree results in an error:
![image](https://user-images.githubusercontent.com/15239509/166164319-fab5a882-e3f7-4735-8f60-e08c68d2790b.png)

**Comment by stevearc** [comment]
This is something that *used* to work, but must have regressed at some point. Should be fixed now

**Comment by krishnakumarg1984** [comment]
Thank you. Indeed it works now. For robustness, is it worth adding a regression test for this issue?

**Comment by stevearc** [comment]
It would be nice to have, but would take some time and I have other tasks (in general, but also on aerial) that I think are higher priority

**Comment by ronandalton** [comment]
Did this stop working again? I'm having the same issue on Neovim 1.10.0. `:q` seems to work but `ctrl-w q` and `ZQ`/`ZZ` don't.
