### ISSUE TITLE
In a layout with multiple splits, automatically refresh the symbols tree for the currently focused split (and dim the aerial window if no symbols tree is found)

### ISSUE THREAD

**Issue by krishnakumarg1984** [stevearc/aerial.nvim#96]
**Description**
Currently, aerial does not automatically update the symbols tree when a new file is opened in a split, and it continues to show the non-relevant symbols pertaining to the original buffer from which aerial was opened.

The desired behavior is that whenever focussing on a new split, `aerial` should refresh the symbols tree and update the aerial window accordingly. Additionally, it would be prudent to have a `:AerialRefresh` command to manually trigger a refresh at the user's will.  

If the file contents in the currently focused split does not have TS/LSP powered symbols available, then the aerial window must be cleared (with the built-in help notice warning that no valid symbols exist for the currently active buffer) and could be dimmed to provide further visual cue to the user. The dimming as an optional feature, could be faciliated by co-operating with a dedicated window dimming plugin such as [shade.nvim](https://github.com/sunjon/Shade.nvim) (if already installed by the user). 

**System information**
- OS: Linux
- Neovim version:
- AerialInfo:
```
Filetype: lua
Configured backends:
  treesitter (supported) (attached)
  lsp (not supported) [LSP client not attached]
  markdown (not supported) [Filetype is not markdown]
Show symbols: Array, Boolean, Class, Constant, Constructor, Enum, EnumMember, Event, Field, File, Function, Interface, Key, Method, Module, Namespace, Null, Number, Object, Operator, Package, Property, String, Struct, TypeParameter, Variable
```
- Aerial config:
```lua
require("aerial").setup({
      backends = { "treesitter", "lsp", "markdown" },
      min_width = 20,
      on_attach = function(bufnr)
        -- Jump forwards/backwards with '{' and '}'
        vim.keymap.set('n', "}", "}", { silent = true })
        vim.keymap.del("n", "}")
        vim.keymap.set("n", "<leader>{", "<cmd>AerialPrev<cr>", { buffer = bufnr, desc = "Jump backwards in Aerial" })
        vim.keymap.set("n", "<leader>}", "<cmd>AerialNext<cr>", { buffer = bufnr, desc = "Jump forwards in Aerial" })
        -- Jump up the tree with '[[' or ']]'
        vim.keymap.set('n', "]]", "]]", { silent = true })
        vim.keymap.del("n", "]]")
        vim.keymap.set('n', "[[", "[[", { silent = true })
        vim.keymap.del("n", "[[")
        vim.keymap.set("n", "<leader>[", "<cmd>AerialPrevUp<cr>", { buffer = bufnr, desc = "Jump up and backwards in Aerial" })
        vim.keymap.set("n", "<leader>]", "<cmd>AerialNextUp<cr>", { buffer = bufnr, desc = "Jump up and forwards in Aerial" })
      end,
      placement_editor_edge = true,
      open_automatic = function(bufnr)
        -- Enforce a minimum line count
        return vim.api.nvim_buf_line_count(bufnr) > 26
          -- Enforce a minimum symbol count
          and require("aerial").num_symbols(bufnr) > 3
          -- -- A useful way to keep aerial closed when closed manually
          and not require("aerial").was_closed()
      end,
      close_behavior = "close", -- aerial window will close when original file is no longer visible
})
```

**Screenshots**
1. Initial `init.lua` file opened with corresponding symbols displayed by aerial
![image](https://user-images.githubusercontent.com/15239509/166504172-321e6424-67bc-48a8-a588-f3138a7f6dc1.png)
2. Now, a `C++` file is opened in the vertical split. However, the original symbols tree is still persisting in the aerial window, which could be confusing if two similar filetypes were opened with just a small diff between them.
![image](https://user-images.githubusercontent.com/15239509/166504524-e96a7473-2f63-43a9-9890-49181a005956.png)
3. Now, a plain-text file without any TS/LSP symbols is opened in the same split. The aerial window is still not refreshed, and continues to show the outdated symbols from `init.lua`. The symbols tree window should have been wiped clean and the built-in help text equivalent to ""No symbols found for the current buffer" ahould be displayed (and optionally the aerial window dimmed).
![image](https://user-images.githubusercontent.com/15239509/166505178-6633d960-6522-485b-85cc-96249d2dbcf5.png)

**Comment by stevearc** [comment]
You should check out the `close_behavior` option. There's a few possibilities, but I think `close_behavior = 'global'` might be the closest to what you want.

**Comment by krishnakumarg1984** [comment]
Yup. `close_behaviour = "global"` does indeed work! Thank you
