### ISSUE TITLE
Implement a was_hidden() method along the lines of was_closed

### ISSUE THREAD

**Issue by krishnakumarg1984** [stevearc/aerial.nvim#99]
In my aerial config, I currently have custom open_automatic implemented as the following function:

```lua
open_automatic = function(bufnr)
return not vim.opt.diff:get()                   -- if not in 'diff' mode
  and vim.api.nvim_buf_line_count(bufnr) > 26   -- Enforce a minimum line count
  and require("aerial").num_symbols(bufnr) > 3  -- Enforce a minimum symbol count
  and not require("aerial").was_closed()        -- A useful way to keep aerial closed when closed manually
end,
```

This helps to prevent the aerial window from annoyingly opening again when it has been manually closed once during the current session with `:AerialClose` or `:AerialToggle` etc. However, this does not consider the scenario wherein the aerial window is merely hidden.

Consider the following scenario. Let's say we are editing a bunch of files in splits, one of them with a symbol table opened. When editing some other buffer, we use the built-in `<C-W>o` or `:only` facilities to quickly hide all other distracting splits to focus on a particular split. Later, when cycling between buffers, say we navigate back to the buffer with symbols, the aerial window automatically reappears unexpectedly, which is jarring visually and throws one off.

Is there a `was_hidden()` method, a logical companion to `was_closed()` method available that I can use in my custom open function? If not, can you please consider facilitating this?

**Comment by stevearc** [comment]
`vim.keymap.set('n', '<C-w>o', '<C-w>o:AerialClose<CR>')`

**Comment by krishnakumarg1984** [comment]
> 

Does this cover the `:only` command, and other ways of hiding the `aerial` window? Isn't it more robust to have a `was_hidden()` method in aerial itself that can leveraged in the user's config?

**Comment by stevearc** [comment]
Yes, but this is another case where the ask is very tied to your workflow. Adding this feature would take a nontrivial amount of time to make sure that it plays nice or even makes sense with all the other config options (e.g. close_behavior, prefer_direction = 'float', etc). Whereas you have a specific workflow you want to enable, with a specific set of config options. This is something that should live in your own vimfiles.
